const VERSION='v0.000.002';
const OLD_KEY='tsumoriq-data-v0.000.001';
const KEY='vialego-data-v0.000.002';
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const fmtMonth=d=>d.toLocaleDateString('nl-BE',{month:'long',year:'numeric'});
const money=(n,c='€')=>`${c}${Number(n||0).toFixed(2).replace('.',',')}`;
const labels=()=>state.settings.distanceUnit==='mi'?{unit:'mi',distance:'Miles'}:{unit:'km',distance:'Kilometers'};
const defaultSettings={name:'',currency:'€',distanceUnit:'km',language:'nl',distance:0,home:'Thuis',home1:'Thuis',home2:'',home3:'',work:'Werk',mode:'Motorfiets'};
const initial={settings:defaultSettings,trips:[],expenses:[],lastBackupReminder:'',lastReportPrompt:''};
let state=load();let viewDate=new Date();let deferredPrompt=null;let pendingWorker=null;

function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem(OLD_KEY)||'{}';const data=JSON.parse(raw);const settings={...defaultSettings,...(data.settings||{})};if(data.settings?.home&&!data.settings?.home1)settings.home1=data.settings.home;return {...initial,...data,settings}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function toast(t,action){const el=document.getElementById('toast');el.innerHTML=action?`${t} <button id="toastAction">${action.label}</button>`:t;el.classList.remove('hidden');if(action)document.getElementById('toastAction').onclick=action.fn;setTimeout(()=>el.classList.add('hidden'),action?6000:2200)}
function setScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(`screen-${name}`).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===name));if(name==='report')renderReport();if(name==='achievements')renderStats()}
function ym(date){return date.toISOString().slice(0,7)}
function inMonth(item){return item.date&&item.date.slice(0,7)===ym(viewDate)}
function monthItems(){return {trips:state.trips.filter(inMonth),expenses:state.expenses.filter(inMonth)}}
function totalKm(list=state.trips){return list.reduce((s,t)=>s+Number(t.km||0),0)}
function clean(v){return String(v||'').trim()}
function routeOptions(){const s=state.settings;return [['home1',s.home1||s.home||'Thuis 1'],['home2',s.home2||'Thuis 2'],['home3',s.home3||'Thuis 3'],['work',s.work||'Werk'],['other','Ander']].filter(([k,v])=>k==='other'||clean(v)&&!/^Thuis [23]$/.test(v))}
function selectedRoute(id,otherId){const el=document.getElementById(id);return el.value==='other'?clean(document.getElementById(otherId).value):el.options[el.selectedIndex]?.text||''}
function setPreset(id,value){const el=document.getElementById(id);[...el.options].forEach((o,i)=>{if(o.text===value||o.value===value)el.selectedIndex=i})}
function updateRouteSelects(){const opts=routeOptions().map(([k,v])=>`<option value="${k}">${v}</option>`).join('');tripFromPreset.innerHTML=opts;tripToPreset.innerHTML=opts;setPreset('tripFromPreset','home1');setPreset('tripToPreset','work');toggleOtherRoutes()}
function toggleOtherRoutes(){tripFromOther.classList.toggle('hidden',tripFromPreset.value!=='other');tripToOther.classList.toggle('hidden',tripToPreset.value!=='other')}
function render(){document.getElementById('currentMonthLabel').textContent=fmtMonth(viewDate);const {trips,expenses}=monthItems();const km=totalKm(trips);const cost=expenses.reduce((s,e)=>s+Number(e.amount||0),0);document.getElementById('statTrips').textContent=trips.length;document.getElementById('statDistanceLabel').textContent=labels().unit;document.getElementById('statKm').textContent=km.toFixed(1).replace('.',',');document.getElementById('statCost').textContent=money(cost,state.settings.currency);document.getElementById('statReceipts').textContent=expenses.filter(e=>e.receipt).length;document.getElementById('tripDistanceLabel').textContent=labels().distance;renderGreeting();renderRecent();fillSettings();if(document.getElementById('screen-report').classList.contains('active'))renderReport();if(document.getElementById('screen-achievements').classList.contains('active'))renderStats()}
function renderGreeting(){const name=state.settings.name||'daar';document.getElementById('greeting').textContent=`Goedemorgen ${name} 👋`;const today=todayISO();const logged=[...state.trips,...state.expenses].some(x=>x.date===today);const streak=calcStreak();document.getElementById('streakText').textContent=logged?`Vandaag gelogd. ${streak} dagen streak.`:`Vandaag nog niets gelogd.`;document.getElementById('motivation').textContent=streak>0?`Goed bezig. Je administratie is al ${streak} dag(en) consequent.`:'Begin met één tik. Ook thuiswerk telt.'}
function calcStreak(){let d=new Date();let count=0;while(true){const iso=d.toISOString().slice(0,10);const has=[...state.trips,...state.expenses].some(x=>x.date===iso);if(!has)break;count++;d.setDate(d.getDate()-1)}return count}
function renderRecent(){const list=document.getElementById('recentList');const rows=[...state.trips.map(t=>({...t,type:'trip'})),...state.expenses.map(e=>({...e,type:'expense'}))].sort((a,b)=>(b.createdAt||b.date).localeCompare(a.createdAt||a.date)).slice(0,12);if(!rows.length){list.className='list empty-state';list.textContent='Nog geen logs.';return}list.className='list';list.innerHTML=rows.map(x=>`<div class="log-row"><div><strong>${x.type==='trip'?iconMode(x.mode)+' '+x.mode+' · '+x.purpose:'🧾 '+x.category}</strong><small>${x.date}${x.type==='trip'?' · '+(x.km||0)+' '+labels().unit:' · '+money(x.amount,state.settings.currency)}</small></div><div class="row-actions"><span class="pill">${x.type==='trip'?'rit':'kost'}</span><button class="danger small delete-log" data-type="${x.type}" data-id="${x.id}">Verwijder</button></div></div>`).join('');document.querySelectorAll('.delete-log').forEach(b=>b.onclick=()=>deleteLog(b.dataset.type,b.dataset.id))}
function iconMode(m){return {Motor:'🏍',Motorfiets:'🏍',Auto:'🚗',Fiets:'🚲',OV:'🚆',Trein:'🚆',Bus:'🚌','Te voet':'🚶'}[m]||'➜'}
function quickCommute(mode){const s=state.settings;state.trips.unshift({id:uid(),date:todayISO(),mode,from:s.home1||s.home||'Thuis',to:s.work||'Werk',km:Number(s.distance||0),purpose:'Woon-werk',notes:'Quick log',createdAt:new Date().toISOString()});save();toast(`${mode} woon-werk gelogd`)}
function quickHome(){state.trips.unshift({id:uid(),date:todayISO(),mode:'Thuiswerk',from:'Thuis',to:'Thuis',km:0,purpose:'Thuiswerk',notes:'Thuis gewerkt',createdAt:new Date().toISOString()});save();toast('Thuiswerk gelogd')}
function deleteLog(type,id){if(!confirm('Deze log verwijderen?'))return;if(!confirm('Zeker? Dit kan niet ongedaan gemaakt worden.'))return;const key=type==='trip'?'trips':'expenses';state[key]=state[key].filter(x=>x.id!==id);save();toast('Log verwijderd')}
async function compressImage(file){return new Promise((resolve)=>{const img=new Image();const reader=new FileReader();reader.onload=e=>{img.onload=()=>{const max=900;let w=img.width,h=img.height;if(w>h&&w>max){h*=max/w;w=max}else if(h>max){w*=max/h;h=max}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.72))};img.src=e.target.result};reader.readAsDataURL(file)})}
function modeTotals(trips){const byMode={};trips.forEach(t=>{byMode[t.mode]=(byMode[t.mode]||0)+Number(t.km||0)});return byMode}
function savings(trips){const bike=trips.filter(t=>['Fiets','Trein','Bus','OV','Te voet'].includes(t.mode)).reduce((s,t)=>s+Number(t.km||0),0);return {km:bike,co2:bike*0.17,fuel:bike*0.06,cal:trips.filter(t=>t.mode==='Fiets').reduce((s,t)=>s+Number(t.km||0)*32,0)}}
function renderReport(){const {trips,expenses}=monthItems();const currency=state.settings.currency;const byMode=modeTotals(trips);const byPurpose={};expenses.forEach(e=>{byPurpose[e.purpose]=(byPurpose[e.purpose]||0)+Number(e.amount||0)});const sav=savings(trips);const receiptRows=expenses.filter(e=>e.receipt).map(e=>`<div class="receipt-block"><strong>${e.date} · ${e.category} · ${money(e.amount,currency)}</strong><img src="${e.receipt}" alt="Bonnetje"></div>`).join('')||'<p>Geen bonnetjes toegevoegd.</p>';const html=`<h2>${state.settings.name||'Gebruiker'} · ${fmtMonth(viewDate)}</h2><p>Vialego rapport, gegenereerd op ${new Date().toLocaleDateString('nl-BE')}.</p><h3>Samenvatting</h3><table class="report-table"><tr><th>Ritten</th><td>${trips.length}</td></tr><tr><th>Afstand</th><td>${totalKm(trips).toFixed(1)} ${labels().unit}</td></tr><tr><th>Kosten</th><td>${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),currency)}</td></tr><tr><th>Bonnetjes</th><td>${expenses.filter(e=>e.receipt).length}</td></tr><tr><th>Geschatte besparing</th><td>${sav.co2.toFixed(1)} kg CO₂ · ${sav.fuel.toFixed(1)} L benzine · ${Math.round(sav.cal)} kcal</td></tr></table><h3>Afstand per vervoer</h3><table class="report-table">${Object.entries(byMode).map(([k,v])=>`<tr><th>${k}</th><td>${v.toFixed(1)} ${labels().unit}</td></tr>`).join('')||'<tr><td>Geen ritten</td></tr>'}</table><h3>Kosten per type</h3><table class="report-table">${Object.entries(byPurpose).map(([k,v])=>`<tr><th>${k}</th><td>${money(v,currency)}</td></tr>`).join('')||'<tr><td>Geen kosten</td></tr>'}</table><h3>Ritten</h3><table class="report-table"><tr><th>Datum</th><th>Vervoer</th><th>Van → Naar</th><th>Afstand</th><th>Type</th></tr>${trips.map(t=>`<tr><td>${t.date}</td><td>${t.mode}</td><td>${t.from||''} → ${t.to||''}</td><td>${t.km||0} ${labels().unit}</td><td>${t.purpose}</td></tr>`).join('')}</table><h3>Kosten</h3><table class="report-table"><tr><th>Datum</th><th>Categorie</th><th>Vervoer</th><th>Bedrag</th><th>Type</th><th>Bon</th></tr>${expenses.map(e=>`<tr><td>${e.date}</td><td>${e.category}</td><td>${e.mode}</td><td>${money(e.amount,currency)}</td><td>${e.purpose}</td><td>${e.receipt?'Ja':'Nee'}</td></tr>`).join('')}</table><h3>Bonnetjes</h3><div class="receipt-report">${receiptRows}</div><p style="margin-top:28px">Handtekening / controle: ___________________________</p>`;document.getElementById('reportContent').innerHTML=html}
function reportText(){const {trips,expenses}=monthItems();const sav=savings(trips);return `Vialego rapport ${fmtMonth(viewDate)}\nRitten: ${trips.length}\nAfstand: ${totalKm(trips).toFixed(1)} ${labels().unit}\nKosten: ${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),state.settings.currency)}\nBonnetjes: ${expenses.filter(e=>e.receipt).length}\nGeschat bespaard: ${sav.co2.toFixed(1)} kg CO2, ${sav.fuel.toFixed(1)} L benzine, ${Math.round(sav.cal)} kcal\n\nOpen de app om het volledige rapport inclusief bonnetjes als PDF te printen.`}
function renderStats(){const {trips,expenses}=monthItems();const byMode=modeTotals(trips);const total=totalKm(trips);const sav=savings(trips);const bars=Object.entries(byMode).sort((a,b)=>b[1]-a[1]).map(([m,v])=>`<div class="bar-row"><span>${iconMode(m)} ${m}</span><div class="bar"><i style="width:${total?Math.round(v/total*100):0}%"></i></div><strong>${total?Math.round(v/total*100):0}%</strong></div>`).join('')||'<p class="muted">Nog geen ritten deze maand.</p>';document.getElementById('statsPanel').innerHTML=`<div class="card"><h3>Vervoermix deze maand</h3>${bars}</div><div class="card"><h3>Totalen</h3><table class="report-table"><tr><th>Transport deze maand</th><td>${total.toFixed(1)} ${labels().unit}</td></tr><tr><th>Transport totaal</th><td>${totalKm().toFixed(1)} ${labels().unit}</td></tr><tr><th>Bonnetjes opgeladen</th><td>${state.expenses.filter(e=>e.receipt).length}</td></tr><tr><th>Kosten deze maand</th><td>${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),state.settings.currency)}</td></tr></table></div><div class="card"><h3>Geschatte impact</h3><p class="muted">Door fiets/openbaar vervoer/te voet te loggen tegenover een fictieve autorit:</p><table class="report-table"><tr><th>Afstand anders dan auto/motor</th><td>${sav.km.toFixed(1)} ${labels().unit}</td></tr><tr><th>CO₂ vermeden</th><td>${sav.co2.toFixed(1)} kg</td></tr><tr><th>Benzine bespaard</th><td>${sav.fuel.toFixed(1)} L</td></tr><tr><th>Calorieën fiets</th><td>${Math.round(sav.cal)} kcal</td></tr></table></div>`}
function fillSettings(){const s=state.settings;settingName.value=s.name||'';settingCurrency.value=s.currency||'€';settingDistanceUnit.value=s.distanceUnit||'km';settingLanguage.value=s.language||'nl';settingDistance.value=s.distance||'';settingHome1.value=s.home1||s.home||'';settingHome2.value=s.home2||'';settingHome3.value=s.home3||'';settingWork.value=s.work||'';settingMode.value=s.mode||'Motorfiets'}
function setTodayInputs(){tripDate.value=todayISO();expenseDate.value=todayISO();tripKm.value=state.settings.distance||'';tripMode.value=state.settings.mode||'Motorfiets';updateRouteSelects()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});
installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;installBtn.classList.add('hidden')}};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen));
document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>b.dataset.action==='workhome'?quickHome():quickCommute(b.dataset.mode));
openTripForm.onclick=()=>{setScreen('log');document.querySelector('[data-tab="trip"]').click()};openExpenseForm.onclick=()=>{setScreen('log');document.querySelector('[data-tab="expense"]').click()};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');tripForm.classList.toggle('active-form',t.dataset.tab==='trip');expenseForm.classList.toggle('active-form',t.dataset.tab==='expense')});
prevMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};nextMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};
tripFromPreset.onchange=toggleOtherRoutes;tripToPreset.onchange=toggleOtherRoutes;swapRoute.onclick=()=>{const f=tripFromPreset.value,t=tripToPreset.value,fo=tripFromOther.value,to=tripToOther.value;tripFromPreset.value=t;tripToPreset.value=f;tripFromOther.value=to;tripToOther.value=fo;toggleOtherRoutes()};
tripForm.onsubmit=e=>{e.preventDefault();state.trips.unshift({id:uid(),date:tripDate.value,mode:tripMode.value,from:selectedRoute('tripFromPreset','tripFromOther'),to:selectedRoute('tripToPreset','tripToOther'),km:Number(tripKm.value||0),purpose:tripPurpose.value,notes:tripNotes.value,createdAt:new Date().toISOString()});tripNotes.value='';save();toast('Rit opgeslagen')};
receiptFile.onchange=async e=>{const f=e.target.files[0];if(f){receiptPreview.src=await compressImage(f);receiptPreview.classList.remove('hidden')}};
expenseForm.onsubmit=e=>{e.preventDefault();state.expenses.unshift({id:uid(),date:expenseDate.value,category:expenseCategory.value,mode:expenseMode.value,amount:Number(expenseAmount.value||0),purpose:expensePurpose.value,notes:expenseNotes.value,receipt:receiptPreview.src||'',createdAt:new Date().toISOString()});expenseAmount.value='';expenseNotes.value='';receiptFile.value='';receiptPreview.src='';receiptPreview.classList.add('hidden');save();toast('Kost opgeslagen')};
settingsForm.onsubmit=e=>{e.preventDefault();state.settings={...state.settings,name:settingName.value,currency:settingCurrency.value,distanceUnit:settingDistanceUnit.value,language:settingLanguage.value,distance:Number(settingDistance.value||0),home:settingHome1.value||'Thuis',home1:settingHome1.value||'Thuis',home2:settingHome2.value,home3:settingHome3.value,work:settingWork.value||'Werk',mode:settingMode.value};save();setTodayInputs();toast('Setup opgeslagen')};
printReport.onclick=()=>window.print();emailReport.onclick=()=>{location.href=`mailto:?subject=${encodeURIComponent('Vialego rapport '+fmtMonth(viewDate))}&body=${encodeURIComponent(reportText())}`};
exportJson.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vialego-backup-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href)};
importJson.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);state={...initial,...data,settings:{...defaultSettings,...(data.settings||{})}};save();setTodayInputs();toast('Backup geïmporteerd')}catch{toast('Ongeldig JSON-bestand')}};r.readAsText(f)};
clearData.onclick=()=>{if(confirm('Alles verwijderen?')&&confirm('Zeker? Alle ritten, kosten en bonnetjes verdwijnen.')){state=structuredClone(initial);save();setTodayInputs();toast('Data gewist')}};
checkUpdates.onclick=()=>navigator.serviceWorker?.getRegistration().then(r=>r?.update().then(()=>toast('Updatecheck uitgevoerd')));
if('serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js').then(reg=>{reg.addEventListener('updatefound',()=>{const nw=reg.installing;nw?.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller){pendingWorker=nw;toast('Nieuwe versie beschikbaar',{label:'Laden',fn:()=>{pendingWorker.postMessage({type:'SKIP_WAITING'});location.reload()}})}})});navigator.serviceWorker.addEventListener('controllerchange',()=>{})})}
setTodayInputs();render();
