const VERSION='v0.000.003';
const VIALEGO_API='https://vialego-api.studiosampersand.workers.dev';
const OLD_KEY='tsumoriq-data-v0.000.001';
const KEY='vialego-data-v0.000.003';
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const fmtMonth=d=>d.toLocaleDateString('nl-BE',{month:'long',year:'numeric'});
const money=(n,c='€')=>`${c}${Number(n||0).toFixed(2).replace('.',',')}`;
const labels=()=>state.settings.distanceUnit==='mi'?{unit:'mi',distance:'Miles'}:{unit:'km',distance:'Kilometers'};
const defaultSettings={name:'',currency:'€',distanceUnit:'km',language:'nl',distance:0,home:'Thuis',home1:'Thuis',home2:'',home3:'',work:'Werk',mode:'Motorfiets'};
const initial={settings:defaultSettings,trips:[],expenses:[],lastBackupReminder:'',lastReportPrompt:''};
let state=load();let viewDate=new Date();let deferredPrompt=null;let pendingWorker=null;let quickDirection='toWork';let showAllLogs=false;let editingType=null;let editingId=null;

function load(){try{const raw=localStorage.getItem(KEY)||localStorage.getItem('vialego-data-v0.000.002')||localStorage.getItem(OLD_KEY)||'{}';const data=JSON.parse(raw);const settings={...defaultSettings,...(data.settings||{})};if(data.settings?.home&&!data.settings?.home1)settings.home1=data.settings.home;return {...initial,...data,settings}}catch{return structuredClone(initial)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function toast(t,action){const el=document.getElementById('toast');el.innerHTML=action?`${t} <button id="toastAction">${action.label}</button>`:t;el.classList.remove('hidden');if(action)document.getElementById('toastAction').onclick=action.fn;setTimeout(()=>el.classList.add('hidden'),action?6000:2200)}
function setScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(`screen-${name}`).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.screen===name));if(name==='report')renderReport();if(name==='achievements')renderStats()}
function ym(date){return date.toISOString().slice(0,7)}
function inMonth(item){return item.date&&item.date.slice(0,7)===ym(viewDate)}
function monthItems(){return {trips:state.trips.filter(inMonth),expenses:state.expenses.filter(inMonth)}}
function totalKm(list=state.trips){return list.reduce((s,t)=>s+Number(t.km||0),0)}
function clean(v){return String(v||'').trim()}
function routeOptions(){const s=state.settings;return [['home1',s.home1||s.home||'Thuis 1'],['home2',s.home2||'Thuis 2'],['home3',s.home3||'Thuis 3'],['work',s.work||'Werk'],['other','Ander']].filter(([k,v])=>k==='other'||clean(v)&&!/^Thuis [23]$/.test(v))}
function selectedRoute(id,otherId){const el=document.getElementById(id);return el.value==='other'?clean(document.getElementById(otherId).value):el.options[el.selectedIndex]?.text||''}
function setPreset(id,value){const el=document.getElementById(id);[...el.options].forEach((o,i)=>{if(o.text===value||o.value===value)el.selectedIndex=i})}
function updateRouteSelects(){const opts=routeOptions().map(([k,v])=>`<option value="${k}">${v}</option>`).join('');tripFromPreset.innerHTML=opts;tripToPreset.innerHTML=opts;setPreset('tripFromPreset','home1');setPreset('tripToPreset','work');toggleOtherRoutes()}
function toggleOtherRoutes(){tripFromOther.classList.toggle('hidden',tripFromPreset.value!=='other');tripToOther.classList.toggle('hidden',tripToPreset.value!=='other')}
function render(){document.getElementById('currentMonthLabel').textContent=fmtMonth(viewDate);const {trips,expenses}=monthItems();const km=totalKm(trips);const cost=expenses.reduce((s,e)=>s+Number(e.amount||0),0);document.getElementById('statTrips').textContent=trips.length;document.getElementById('statDistanceLabel').textContent=labels().unit;document.getElementById('statKm').textContent=km.toFixed(1).replace('.',',');document.getElementById('statCost').textContent=money(cost,state.settings.currency);document.getElementById('statReceipts').textContent=[...trips,...expenses].filter(e=>e.receipt).length;document.getElementById('tripDistanceLabel').textContent=labels().distance;renderGreeting();renderRecent();fillSettings();if(document.getElementById('screen-report').classList.contains('active'))renderReport();if(document.getElementById('screen-achievements').classList.contains('active'))renderStats()}
function renderGreeting(){const name=state.settings.name||'daar';document.getElementById('greeting').textContent=`Goedemorgen ${name} 👋`;const today=todayISO();const logged=[...state.trips,...state.expenses].some(x=>x.date===today);const streak=calcStreak();document.getElementById('streakText').textContent=logged?`Vandaag gelogd. ${streak} dagen streak.`:`Vandaag nog niets gelogd.`;document.getElementById('motivation').textContent=streak>0?`Goed bezig. Je administratie is al ${streak} dag(en) consequent.`:'Begin met één tik. Ook thuiswerk telt.'}
function calcStreak(){let d=new Date();let count=0;while(true){const iso=d.toISOString().slice(0,10);const has=[...state.trips,...state.expenses].some(x=>x.date===iso);if(!has)break;count++;d.setDate(d.getDate()-1)}return count}
function renderRecent(){const list=document.getElementById('recentList');const all=[...state.trips.map(t=>({...t,type:'trip'})),...state.expenses.map(e=>({...e,type:'expense'}))].sort((a,b)=>(b.createdAt||b.date).localeCompare(a.createdAt||a.date));const rows=showAllLogs?all:all.slice(0,8);viewAllLogs.textContent=showAllLogs?'Minder':'Alles';if(!rows.length){list.className='list empty-state';list.textContent='Nog geen logs.';return}list.className='list';list.innerHTML=rows.map(x=>`<div class="log-row"><div><strong>${x.type==='trip'?iconMode(x.mode)+' '+x.mode+' · '+x.purpose:'🧾 '+x.category}</strong><small>${x.date}${x.type==='trip'?' · '+(x.km||0)+' '+labels().unit:' · '+money(x.amount,state.settings.currency)}${x.receipt?' · 📎':''}</small></div><div class="row-actions"><span class="pill">${x.type==='trip'?'rit':'kost'}</span><button class="ghost small edit-log" data-type="${x.type}" data-id="${x.id}">Edit</button><button class="danger small delete-log" data-type="${x.type}" data-id="${x.id}">Verwijder</button></div></div>`).join('');document.querySelectorAll('.edit-log').forEach(b=>b.onclick=()=>editLog(b.dataset.type,b.dataset.id));document.querySelectorAll('.delete-log').forEach(b=>b.onclick=()=>deleteLog(b.dataset.type,b.dataset.id))}
function iconMode(m){return {Motor:'🏍',Motorfiets:'🏍',Auto:'🚗',Fiets:'🚲',OV:'🚆',Trein:'🚆',Bus:'🚌','Te voet':'🚶'}[m]||'➜'}
function updateQuickDirection(){const toWork=quickDirection==='toWork';quickToWork.classList.toggle('active',toWork);quickToHome.classList.toggle('active',!toWork);heroCommuteButton.textContent=toWork?'🏍 Motor naar werk':'🏍 Motor naar huis'}
function quickCommute(mode){const s=state.settings;const home=s.home1||s.home||'Thuis';const work=s.work||'Werk';const toWork=quickDirection==='toWork';const item={id:uid(),date:todayISO(),mode,from:toWork?home:work,to:toWork?work:home,km:Number(s.distance||0),purpose:'Woon-werk',notes:'Quick log',receipt:'',createdAt:new Date().toISOString()};state.trips.unshift(item);save();toast(`${mode}: ${toWork?'naar werk':'naar huis'} gelogd`,{label:'Aanpassen',fn:()=>editLog('trip',item.id)})}
function quickHome(){state.trips.unshift({id:uid(),date:todayISO(),mode:'Thuiswerk',from:'Thuis',to:'Thuis',km:0,purpose:'Thuiswerk',notes:'Thuis gewerkt',createdAt:new Date().toISOString()});save();toast('Thuiswerk gelogd')}
function resetEditing(){editingType=null;editingId=null;tripSubmitButton.textContent='Rit opslaan';expenseSubmitButton.textContent='Kost opslaan'}
function findRoutePreset(value){const match=[...tripFromPreset.options].find(o=>o.text===value);return match?match.value:'other'}
function editLog(type,id){const key=type==='trip'?'trips':'expenses';const item=state[key].find(x=>x.id===id);if(!item)return;editingType=type;editingId=id;setScreen('log');document.querySelector(`[data-tab="${type==='trip'?'trip':'expense'}"]`).click();if(type==='trip'){updateRouteSelects();tripDate.value=item.date||todayISO();tripMode.value=item.mode||'Motorfiets';tripFromPreset.value=findRoutePreset(item.from);tripToPreset.value=findRoutePreset(item.to);tripFromOther.value=tripFromPreset.value==='other'?(item.from||''):'';tripToOther.value=tripToPreset.value==='other'?(item.to||''):'';toggleOtherRoutes();tripKm.value=item.km||0;tripPurpose.value=item.purpose||'Woon-werk';tripNotes.value=item.notes||'';setReceiptPreview(tripReceiptPreview,item.receipt);tripSubmitButton.textContent='Wijzigingen opslaan'}else{expenseDate.value=item.date||todayISO();expenseCategory.value=item.category||'Anders';expenseMode.value=item.mode||'Anders';expenseAmount.value=item.amount||0;expensePurpose.value=item.purpose||'Privé';expenseNotes.value=item.notes||'';setReceiptPreview(receiptPreview,item.receipt);expenseSubmitButton.textContent='Wijzigingen opslaan'}}
async function loadReceipt(file,preview){if(!file)return;preview.src=await compressImage(file);preview.classList.remove('hidden')}
function deleteLog(type,id){if(!confirm('Deze log verwijderen?'))return;if(!confirm('Zeker? Dit kan niet ongedaan gemaakt worden.'))return;const key=type==='trip'?'trips':'expenses';state[key]=state[key].filter(x=>x.id!==id);save();toast('Log verwijderd')}
async function compressImage(file){return new Promise((resolve)=>{const img=new Image();const reader=new FileReader();reader.onload=e=>{img.onload=()=>{const max=900;let w=img.width,h=img.height;if(w>h&&w>max){h*=max/w;w=max}else if(h>max){w*=max/h;h=max}const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',.72))};img.src=e.target.result};reader.readAsDataURL(file)})}
function modeTotals(trips){const byMode={};trips.forEach(t=>{byMode[t.mode]=(byMode[t.mode]||0)+Number(t.km||0)});return byMode}
function savings(trips){const bike=trips.filter(t=>['Fiets','Trein','Bus','OV','Te voet'].includes(t.mode)).reduce((s,t)=>s+Number(t.km||0),0);return {km:bike,co2:bike*0.17,fuel:bike*0.06,cal:trips.filter(t=>t.mode==='Fiets').reduce((s,t)=>s+Number(t.km||0)*32,0)}}
function storedReceipt(preview){const src=preview.getAttribute('src')||'';return /^data:image\//.test(src)?src:''}
function setReceiptPreview(preview,receipt){if(receipt&&/^data:image\//.test(receipt)){preview.setAttribute('src',receipt);preview.classList.remove('hidden')}else{preview.removeAttribute('src');preview.classList.add('hidden')}}
function renderReport(){const {trips,expenses}=monthItems();const currency=state.settings.currency;const byMode=modeTotals(trips);const byPurpose={};expenses.forEach(e=>{byPurpose[e.purpose]=(byPurpose[e.purpose]||0)+Number(e.amount||0)});const sav=savings(trips);const receiptRows=[...trips.filter(t=>t.receipt).map(t=>`<div class="receipt-block"><strong>${t.date} · ${t.mode} · ${t.from||''} → ${t.to||''}</strong><img src="${t.receipt}" alt="Ticket of bewijs"></div>`),...expenses.filter(e=>e.receipt).map(e=>`<div class="receipt-block"><strong>${e.date} · ${e.category} · ${money(e.amount,currency)}</strong><img src="${e.receipt}" alt="Bonnetje"></div>`)].join('')||'<p>Geen bonnetjes of tickets toegevoegd.</p>';const html=`<h2>${state.settings.name||'Gebruiker'} · ${fmtMonth(viewDate)}</h2><p>Vialego rapport, gegenereerd op ${new Date().toLocaleDateString('nl-BE')}.</p><h3>Samenvatting</h3><table class="report-table"><tr><th>Ritten</th><td>${trips.length}</td></tr><tr><th>Afstand</th><td>${totalKm(trips).toFixed(1)} ${labels().unit}</td></tr><tr><th>Kosten</th><td>${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),currency)}</td></tr><tr><th>Bonnetjes/tickets</th><td>${[...trips,...expenses].filter(e=>e.receipt).length}</td></tr><tr><th>Geschatte besparing</th><td>${sav.co2.toFixed(1)} kg CO₂ · ${sav.fuel.toFixed(1)} L benzine · ${Math.round(sav.cal)} kcal</td></tr></table><h3>Afstand per vervoer</h3><table class="report-table">${Object.entries(byMode).map(([k,v])=>`<tr><th>${k}</th><td>${v.toFixed(1)} ${labels().unit}</td></tr>`).join('')||'<tr><td>Geen ritten</td></tr>'}</table><h3>Kosten per type</h3><table class="report-table">${Object.entries(byPurpose).map(([k,v])=>`<tr><th>${k}</th><td>${money(v,currency)}</td></tr>`).join('')||'<tr><td>Geen kosten</td></tr>'}</table><h3>Ritten</h3><table class="report-table"><tr><th>Datum</th><th>Vervoer</th><th>Van → Naar</th><th>Afstand</th><th>Type</th></tr>${trips.map(t=>`<tr><td>${t.date}</td><td>${t.mode}</td><td>${t.from||''} → ${t.to||''}</td><td>${t.km||0} ${labels().unit}</td><td>${t.purpose}</td></tr>`).join('')}</table><h3>Kosten</h3><table class="report-table"><tr><th>Datum</th><th>Categorie</th><th>Vervoer</th><th>Bedrag</th><th>Type</th><th>Bon</th></tr>${expenses.map(e=>`<tr><td>${e.date}</td><td>${e.category}</td><td>${e.mode}</td><td>${money(e.amount,currency)}</td><td>${e.purpose}</td><td>${e.receipt?'Ja':'Nee'}</td></tr>`).join('')}</table><h3>Bonnetjes en tickets</h3><div class="receipt-report">${receiptRows}</div><p style="margin-top:28px">Handtekening / controle: ___________________________</p>`;document.getElementById('reportContent').innerHTML=html}
function reportText(){const {trips,expenses}=monthItems();const sav=savings(trips);return `Vialego rapport ${fmtMonth(viewDate)}\nRitten: ${trips.length}\nAfstand: ${totalKm(trips).toFixed(1)} ${labels().unit}\nKosten: ${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),state.settings.currency)}\nBonnetjes: ${expenses.filter(e=>e.receipt).length}\nGeschat bespaard: ${sav.co2.toFixed(1)} kg CO2, ${sav.fuel.toFixed(1)} L benzine, ${Math.round(sav.cal)} kcal\n\nOpen de app om het volledige rapport inclusief bonnetjes als PDF te printen.`}
function renderStats(){const {trips,expenses}=monthItems();const byMode=modeTotals(trips);const total=totalKm(trips);const year=String(viewDate.getFullYear());const yearTrips=state.trips.filter(t=>t.date&&t.date.startsWith(year));const yearTotal=totalKm(yearTrips);const sav=savings(trips);const entries=Object.entries(byMode).sort((a,b)=>b[1]-a[1]);const bars=entries.map(([m,v])=>`<div class="bar-row"><span>${iconMode(m)} ${m}</span><div class="bar"><i style="width:${total?Math.round(v/total*100):0}%"></i></div><strong>${total?Math.round(v/total*100):0}%</strong></div>`).join('')||'<p class="muted">Nog geen ritten deze maand.</p>';let cursor=0;const slices=entries.map(([m,v],i)=>{const start=cursor;cursor+=total?v/total*100:0;return `var(--chart-${i%6}) ${start}% ${cursor}%`}).join(',');const pie=total?`<div class="pie" style="background:conic-gradient(${slices})"><span>${total.toFixed(1)}<small>${labels().unit}</small></span></div>`:'<div class="pie empty-pie"><span>0<small>'+labels().unit+'</small></span></div>';document.getElementById('statsPanel').innerHTML=`<div class="card"><h3>Vervoermix deze maand</h3><div class="chart-wrap">${pie}<div>${bars}</div></div></div><div class="card"><h3>Totalen</h3><table class="report-table"><tr><th>Transport deze maand</th><td>${total.toFixed(1)} ${labels().unit}</td></tr><tr><th>Transport dit jaar</th><td>${yearTotal.toFixed(1)} ${labels().unit}</td></tr><tr><th>Transport totaal</th><td>${totalKm().toFixed(1)} ${labels().unit}</td></tr><tr><th>Bonnetjes/tickets opgeladen</th><td>${[...state.trips,...state.expenses].filter(e=>e.receipt).length}</td></tr><tr><th>Kosten deze maand</th><td>${money(expenses.reduce((s,e)=>s+Number(e.amount||0),0),state.settings.currency)}</td></tr></table></div><div class="card"><h3>Geschatte impact</h3><p class="muted">Schatting tegenover dezelfde afstand met een gemiddelde benzinewagen.</p><table class="report-table"><tr><th>Afstand fiets/OV/te voet</th><td>${sav.km.toFixed(1)} ${labels().unit}</td></tr><tr><th>CO₂ vermeden</th><td>${sav.co2.toFixed(1)} kg</td></tr><tr><th>Benzine bespaard</th><td>${sav.fuel.toFixed(1)} L</td></tr><tr><th>Calorieën fiets</th><td>${Math.round(sav.cal)} kcal</td></tr></table></div>`}
async function shareReport(){renderReport();const content=document.getElementById('reportContent').innerHTML;const html=`<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Vialego rapport ${fmtMonth(viewDate)}</title><style>body{font:15px Arial,sans-serif;color:#111;max-width:900px;margin:30px auto;padding:0 18px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}.receipt-report{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.receipt-block{break-inside:avoid;border:1px solid #ddd;padding:10px;border-radius:12px}.receipt-block img{width:100%;max-height:420px;object-fit:contain;margin-top:8px}@media(max-width:600px){.receipt-report{grid-template-columns:1fr}}</style></head><body>${content}</body></html>`;const file=new File([html],`vialego-rapport-${ym(viewDate)}.html`,{type:'text/html'});if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({title:`Vialego rapport ${fmtMonth(viewDate)}`,text:'Volledig Vialego-rapport inclusief bonnetjes.',files:[file]});return}const a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);location.href=`mailto:?subject=${encodeURIComponent('Vialego rapport '+fmtMonth(viewDate))}&body=${encodeURIComponent(reportText()+'\n\nHet volledige rapport inclusief bonnetjes werd als HTML-bestand klaargezet om toe te voegen.')}`}

const addressTimers=new WeakMap();
const addressControllers=new WeakMap();
function photonLabel(properties={}){const first=[properties.name,properties.street&&properties.housenumber?`${properties.street} ${properties.housenumber}`:properties.street].filter(Boolean)[0]||'';const locality=[properties.postcode,properties.city||properties.town||properties.village||properties.locality].filter(Boolean).join(' ');return [first,locality,properties.country].filter(Boolean).join(', ')}
function closeAddressResults(input){const box=input.parentElement.querySelector('.address-results');box.classList.add('hidden');box.innerHTML='';input.setAttribute('aria-expanded','false')}
function showAddressMessage(input,message){const box=input.parentElement.querySelector('.address-results');box.innerHTML=`<div class="address-option" aria-disabled="true">${message}</div>`;box.classList.remove('hidden');input.setAttribute('aria-expanded','true')}
async function searchAddresses(input){const query=clean(input.value);if(query.length<3){closeAddressResults(input);return}addressControllers.get(input)?.abort();const controller=new AbortController();addressControllers.set(input,controller);showAddressMessage(input,'Adressen zoeken…');try{const url=`${VIALEGO_API}/geocode?text=${encodeURIComponent(query)}&_=${Date.now()}`;const response=await fetch(url,{signal:controller.signal,mode:'cors',credentials:'omit',cache:'no-store',headers:{Accept:'application/json'}});const raw=await response.text();if(!response.ok){console.error('Vialego geocode error',response.status,raw);throw new Error(`HTTP ${response.status}`)}let data;try{data=JSON.parse(raw)}catch{throw new Error('Ongeldig antwoord')}const suggestions=(data.features||[]).map(feature=>({label:feature.properties?.label||feature.properties?.name||'',coordinates:feature.geometry?.coordinates})).filter(x=>x.label&&Array.isArray(x.coordinates));const unique=[...new Map(suggestions.map(x=>[x.label,x])).values()].slice(0,5);const box=input.parentElement.querySelector('.address-results');if(!unique.length){showAddressMessage(input,'Geen adressen gevonden. Voeg ook gemeente of postcode toe, of vul handmatig in.');return}box.innerHTML=unique.map((item,index)=>`<button type="button" class="address-option" role="option" data-address-index="${index}">${item.label}<small>Adresvoorstel</small></button>`).join('');box.classList.remove('hidden');input.setAttribute('aria-expanded','true');box.querySelectorAll('.address-option').forEach((button,index)=>button.onclick=()=>{input.value=unique[index].label;input.dataset.coordinates=JSON.stringify(unique[index].coordinates);closeAddressResults(input);input.dispatchEvent(new Event('change',{bubbles:true}))})}catch(error){if(error.name==='AbortError')return;console.error('Adreszoeker niet bereikbaar',error);showAddressMessage(input,`Adreszoeker niet bereikbaar (${error.message}). Controleer de Cloudflare Worker; handmatig invullen blijft mogelijk.`)}}
function setupAddressSearch(){document.querySelectorAll('.address-search').forEach(input=>{input.addEventListener('input',()=>{clearTimeout(addressTimers.get(input));addressTimers.set(input,setTimeout(()=>searchAddresses(input),450))});input.addEventListener('keydown',event=>{if(event.key==='Escape')closeAddressResults(input)});input.addEventListener('blur',()=>setTimeout(()=>closeAddressResults(input),180))});document.addEventListener('click',event=>{if(!event.target.closest('.address-field'))document.querySelectorAll('.address-search').forEach(closeAddressResults)})}

function fillSettings(){const s=state.settings;settingName.value=s.name||'';settingCurrency.value=s.currency||'€';settingDistanceUnit.value=s.distanceUnit||'km';settingLanguage.value=s.language||'nl';settingDistance.value=s.distance||'';settingHome1.value=s.home1||s.home||'';settingHome2.value=s.home2||'';settingHome3.value=s.home3||'';settingWork.value=s.work||'';settingMode.value=s.mode||'Motorfiets'}
function setTodayInputs(){tripDate.value=todayISO();expenseDate.value=todayISO();tripKm.value=state.settings.distance||'';tripMode.value=state.settings.mode||'Motorfiets';updateRouteSelects()}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;installBtn.classList.remove('hidden')});
installBtn.onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null;installBtn.classList.add('hidden')}};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen));
document.querySelectorAll('.quick').forEach(b=>b.onclick=()=>b.dataset.action==='workhome'?quickHome():quickCommute(b.dataset.mode));
quickToWork.onclick=()=>{quickDirection='toWork';updateQuickDirection()};quickToHome.onclick=()=>{quickDirection='toHome';updateQuickDirection()};
openTripForm.onclick=()=>{resetEditing();setTodayInputs();setScreen('log');document.querySelector('[data-tab="trip"]').click()};openExpenseForm.onclick=()=>{resetEditing();setTodayInputs();setScreen('log');document.querySelector('[data-tab="expense"]').click()};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');tripForm.classList.toggle('active-form',t.dataset.tab==='trip');expenseForm.classList.toggle('active-form',t.dataset.tab==='expense')});
prevMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};nextMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};viewAllLogs.onclick=()=>{showAllLogs=!showAllLogs;renderRecent()};
tripFromPreset.onchange=toggleOtherRoutes;tripToPreset.onchange=toggleOtherRoutes;swapRoute.onclick=()=>{const f=tripFromPreset.value,t=tripToPreset.value,fo=tripFromOther.value,to=tripToOther.value;tripFromPreset.value=t;tripToPreset.value=f;tripFromOther.value=to;tripToOther.value=fo;toggleOtherRoutes()};
tripForm.onsubmit=e=>{e.preventDefault();const data={date:tripDate.value,mode:tripMode.value,from:selectedRoute('tripFromPreset','tripFromOther'),to:selectedRoute('tripToPreset','tripToOther'),km:Number(tripKm.value||0),purpose:tripPurpose.value,notes:tripNotes.value,receipt:storedReceipt(tripReceiptPreview)};if(editingType==='trip'&&editingId){const i=state.trips.findIndex(x=>x.id===editingId);if(i>=0)state.trips[i]={...state.trips[i],...data,updatedAt:new Date().toISOString()}}else state.trips.unshift({id:uid(),...data,createdAt:new Date().toISOString()});resetEditing();tripNotes.value='';tripReceiptFile.value='';tripReceiptCamera.value='';tripReceiptPreview.removeAttribute('src');tripReceiptPreview.classList.add('hidden');save();toast('Rit opgeslagen')};
receiptFile.onchange=e=>loadReceipt(e.target.files[0],receiptPreview);receiptCamera.onchange=e=>loadReceipt(e.target.files[0],receiptPreview);tripReceiptFile.onchange=e=>loadReceipt(e.target.files[0],tripReceiptPreview);tripReceiptCamera.onchange=e=>loadReceipt(e.target.files[0],tripReceiptPreview);
expenseForm.onsubmit=e=>{e.preventDefault();const data={date:expenseDate.value,category:expenseCategory.value,mode:expenseMode.value,amount:Number(expenseAmount.value||0),purpose:expensePurpose.value,notes:expenseNotes.value,receipt:storedReceipt(receiptPreview)};if(editingType==='expense'&&editingId){const i=state.expenses.findIndex(x=>x.id===editingId);if(i>=0)state.expenses[i]={...state.expenses[i],...data,updatedAt:new Date().toISOString()}}else state.expenses.unshift({id:uid(),...data,createdAt:new Date().toISOString()});resetEditing();expenseAmount.value='';expenseNotes.value='';receiptFile.value='';receiptCamera.value='';receiptPreview.removeAttribute('src');receiptPreview.classList.add('hidden');save();toast('Kost opgeslagen')};
settingsForm.onsubmit=e=>{e.preventDefault();state.settings={...state.settings,name:settingName.value,currency:settingCurrency.value,distanceUnit:settingDistanceUnit.value,language:settingLanguage.value,distance:Number(settingDistance.value||0),home:settingHome1.value||'Thuis',home1:settingHome1.value||'Thuis',home2:settingHome2.value,home3:settingHome3.value,work:settingWork.value||'Werk',mode:settingMode.value};save();setTodayInputs();toast('Setup opgeslagen')};
printReport.onclick=()=>window.print();emailReport.onclick=()=>shareReport().catch(()=>toast('Delen mislukt. Probeer Print / PDF.'));
exportJson.onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vialego-backup-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href)};
importJson.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);state={...initial,...data,settings:{...defaultSettings,...(data.settings||{})}};save();setTodayInputs();toast('Backup geïmporteerd')}catch{toast('Ongeldig JSON-bestand')}};r.readAsText(f)};
clearData.onclick=()=>{if(confirm('Alles verwijderen?')&&confirm('Zeker? Alle ritten, kosten en bonnetjes verdwijnen.')){state=structuredClone(initial);save();setTodayInputs();toast('Data gewist')}};
function showUpdateBanner(worker){pendingWorker=worker||pendingWorker;const banner=document.getElementById('updateBanner');if(banner)banner.classList.remove('hidden')}
function hideUpdateBanner(){const banner=document.getElementById('updateBanner');if(banner)banner.classList.add('hidden')}
async function applyPendingUpdate(){if(!pendingWorker){const reg=await navigator.serviceWorker.getRegistration();pendingWorker=reg?.waiting||null}if(pendingWorker){pendingWorker.postMessage({type:'SKIP_WAITING'})}else{location.reload()}}
const applyUpdateButton=document.getElementById('applyUpdate');if(applyUpdateButton)applyUpdateButton.onclick=applyPendingUpdate;
checkUpdates.onclick=async()=>{if(!('serviceWorker'in navigator)){toast('Updates worden niet ondersteund op dit toestel');return}const reg=await navigator.serviceWorker.getRegistration();if(!reg){toast('Service worker nog niet actief');return}await reg.update();if(reg.waiting){showUpdateBanner(reg.waiting);toast('Nieuwe versie beschikbaar')}else toast('Je gebruikt de nieuwste versie')};
if('serviceWorker'in navigator){navigator.serviceWorker.register('./service-worker.js').then(reg=>{if(reg.waiting)showUpdateBanner(reg.waiting);reg.addEventListener('updatefound',()=>{const nw=reg.installing;nw?.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller){showUpdateBanner(nw);toast('Nieuwe versie beschikbaar')}})});navigator.serviceWorker.addEventListener('controllerchange',()=>{hideUpdateBanner();location.reload()})}).catch(()=>toast('Updatecontrole kon niet worden gestart'))}
setupAddressSearch();setTodayInputs();render();updateQuickDirection();

/* v0.000.003 launch hardening */
let calendarDate=new Date(viewDate);let selectedCalendarDay=todayISO();
const originalSave=save;
save=function(){try{localStorage.setItem(KEY,JSON.stringify(state));render();return true}catch(error){console.error(error);toast('Opslag is vol. Exporteer een backup en verwijder enkele grote foto’s.');return false}};

function logRowsHtml(rows){return rows.map(x=>`<div class="log-row"><div><strong>${x.type==='trip'?iconMode(x.mode)+' '+x.mode+' · '+x.purpose:'🧾 '+x.category}</strong><small>${x.date}${x.type==='trip'?' · '+(x.km||0)+' '+labels().unit:' · '+money(x.amount,state.settings.currency)}${x.receipt?' · 📎':''}</small></div><div class="row-actions"><span class="pill">${x.type==='trip'?'rit':'kost'}</span><button class="ghost small edit-log" data-type="${x.type}" data-id="${x.id}">Edit</button><button class="danger small delete-log" data-type="${x.type}" data-id="${x.id}">Verwijder</button></div></div>`).join('')}
function bindLogActions(scope=document){scope.querySelectorAll('.edit-log').forEach(b=>b.onclick=()=>editLog(b.dataset.type,b.dataset.id));scope.querySelectorAll('.delete-log').forEach(b=>b.onclick=()=>{deleteLog(b.dataset.type,b.dataset.id);setTimeout(renderCalendar,0)})}
function renderCalendar(){
 const label=document.getElementById('calendarMonthLabel');if(!label)return;label.textContent=fmtMonth(calendarDate);
 const year=calendarDate.getFullYear(),month=calendarDate.getMonth();const first=new Date(year,month,1);const days=new Date(year,month+1,0).getDate();const offset=(first.getDay()+6)%7;
 const counts={};[...state.trips,...state.expenses].forEach(x=>{if(x.date?.slice(0,7)===`${year}-${String(month+1).padStart(2,'0')}`)counts[x.date]=(counts[x.date]||0)+1});
 let html='';for(let i=0;i<offset;i++)html+='<span class="calendar-day blank"></span>';
 for(let d=1;d<=days;d++){const iso=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const c=counts[iso]||0;html+=`<button class="calendar-day ${c?'filled':''} ${iso===todayISO()?'today':''} ${iso===selectedCalendarDay?'selected':''}" data-date="${iso}"><span>${d}</span>${c?`<span class="calendar-count">${c} log${c===1?'':'s'}</span>`:''}</button>`}
 calendarGrid.innerHTML=html;calendarGrid.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{selectedCalendarDay=b.dataset.date;renderCalendar()});
 const dateObj=new Date(selectedCalendarDay+'T12:00:00');calendarDayTitle.textContent=`Registraties · ${dateObj.toLocaleDateString('nl-BE',{weekday:'long',day:'numeric',month:'long'})}`;
 const rows=[...state.trips.filter(x=>x.date===selectedCalendarDay).map(x=>({...x,type:'trip'})),...state.expenses.filter(x=>x.date===selectedCalendarDay).map(x=>({...x,type:'expense'}))].sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));
 calendarDayList.className=rows.length?'list':'list empty-state';calendarDayList.innerHTML=rows.length?logRowsHtml(rows):'Geen registraties op deze dag.';bindLogActions(calendarDayList)
}
viewAllLogs.onclick=()=>{calendarDate=new Date(viewDate);selectedCalendarDay=todayISO().slice(0,7)===ym(calendarDate)?todayISO():`${ym(calendarDate)}-01`;setScreen('calendar');renderCalendar()};
closeCalendar.onclick=()=>setScreen('dashboard');calendarPrev.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);selectedCalendarDay=`${ym(calendarDate)}-01`;renderCalendar()};calendarNext.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);selectedCalendarDay=`${ym(calendarDate)}-01`;renderCalendar()};

async function geocodeAddress(address){const cacheKey=`vialego-geocode:${address.toLowerCase()}`;const cached=localStorage.getItem(cacheKey);if(cached){try{return JSON.parse(cached)}catch{}}const r=await fetch(`${VIALEGO_API}/geocode?text=${encodeURIComponent(address)}`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Adres niet gevonden');const j=await r.json();const coords=j.features?.[0]?.geometry?.coordinates;if(!Array.isArray(coords)||coords.length!==2)throw new Error('Adres niet gevonden');localStorage.setItem(cacheKey,JSON.stringify(coords));return coords}
function routeProfile(mode){if(mode==='Fiets')return 'cycling-regular';if(mode==='Te voet')return 'foot-walking';return 'driving-car'}
async function calculateDistance(from,to,mode){if(!clean(from)||!clean(to)||/^(Thuis|Werk)( \d)?$/.test(from)||/^(Thuis|Werk)( \d)?$/.test(to))throw new Error('Vul eerst volledige adressen in Setup in');const profile=routeProfile(mode);const cacheKey=`vialego-route:${profile}:${from.toLowerCase()}|${to.toLowerCase()}`;const cached=localStorage.getItem(cacheKey);if(cached){const km=Number(cached);return state.settings.distanceUnit==='mi'?km*0.621371:km}const [a,b]=await Promise.all([geocodeAddress(from),geocodeAddress(to)]);const r=await fetch(`${VIALEGO_API}/route`,{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({profile,coordinates:[a,b]})});if(!r.ok)throw new Error('Routeberekening niet bereikbaar');const j=await r.json();const metres=j.features?.[0]?.properties?.summary?.distance;if(!Number.isFinite(metres))throw new Error('Geen route gevonden');const km=metres/1000;localStorage.setItem(cacheKey,String(km));return state.settings.distanceUnit==='mi'?km*0.621371:km}
async function calculateCurrentRoute(){const from=selectedRoute('tripFromPreset','tripFromOther'),to=selectedRoute('tripToPreset','tripToOther'),mode=tripMode.value;calculateRoute.disabled=true;routeCalcStatus.textContent='Route berekenen…';try{const dist=await calculateDistance(from,to,mode);tripKm.value=dist.toFixed(1);routeCalcStatus.textContent=`Kortste beschikbare route: ${dist.toFixed(1)} ${labels().unit}${['Trein','Bus'].includes(mode)?' (wegafstand als benadering)':''}.`}catch(e){routeCalcStatus.textContent=e.message||'Routeberekening mislukt. Vul de afstand handmatig in.'}finally{calculateRoute.disabled=false}}
calculateRoute.onclick=calculateCurrentRoute;tripMode.onchange=()=>{routeCalcStatus.textContent='Vervoer gewijzigd. Bereken de route opnieuw.'};tripFromPreset.addEventListener('change',()=>routeCalcStatus.textContent='Route gewijzigd. Bereken opnieuw.');tripToPreset.addEventListener('change',()=>routeCalcStatus.textContent='Route gewijzigd. Bereken opnieuw.');
quickCommute=async function(mode){const s=state.settings;const home=s.home1||s.home||'Thuis';const work=s.work||'Werk';const toWork=quickDirection==='toWork';const from=toWork?home:work,to=toWork?work:home;let distance=Number(s.distance||0);try{distance=await calculateDistance(from,to,mode)}catch(e){toast(`Route niet berekend: ${e.message}. Standaardafstand gebruikt.`)}const item={id:uid(),date:todayISO(),mode,from,to,km:Number(distance.toFixed(1)),purpose:'Woon-werk',notes:'Quick log',receipt:'',createdAt:new Date().toISOString()};state.trips.unshift(item);if(save())toast(`${mode} · ${item.km} ${labels().unit} · ${toWork?'Woon → Werk':'Werk → Woon'}`,{label:'Aanpassen',fn:()=>editLog('trip',item.id)})};

const oldExport=exportJson.onclick;exportJson.onclick=()=>{state.lastBackupDate=new Date().toISOString();save();oldExport()};
const oldImport=importJson.onchange;importJson.onchange=e=>{if(!confirm('Deze import vervangt je huidige lokale gegevens. Eerst een backup gemaakt?')){e.target.value='';return}oldImport(e)};
clearData.onclick=()=>{if(!confirm('Alles verwijderen?'))return;const typed=prompt('Typ VERWIJDEREN om alle ritten, kosten en bonnetjes definitief te wissen.');if(typed==='VERWIJDEREN'){state=structuredClone(initial);save();setTodayInputs();toast('Data gewist')}else toast('Reset geannuleerd')};
const oldFillSettings=fillSettings;fillSettings=function(){oldFillSettings();const el=document.getElementById('lastBackupText');if(el)el.textContent=`Laatste backup: ${state.lastBackupDate?new Date(state.lastBackupDate).toLocaleString('nl-BE'):'nog niet gemaakt.'}`};
fillSettings();
settingsForm.onsubmit=async e=>{e.preventDefault();const next={...state.settings,name:settingName.value,currency:settingCurrency.value,distanceUnit:settingDistanceUnit.value,language:settingLanguage.value,home:settingHome1.value||'Thuis',home1:settingHome1.value||'Thuis',home2:settingHome2.value,home3:settingHome3.value,work:settingWork.value||'Werk',mode:settingMode.value};state.settings=next;let calculated=false;try{const dist=await calculateDistance(next.home1,next.work,next.mode);state.settings.distance=Number(dist.toFixed(1));calculated=true}catch(error){state.settings.distance=Number(settingDistance.value||state.settings.distance||0)}if(save()){setTodayInputs();toast(calculated?`Setup opgeslagen · route ${state.settings.distance} ${labels().unit}`:'Setup opgeslagen · routeafstand handmatig behouden')}};
