const VERSION='0.000.007';
const KEY='mobud-beta-data-v0.000.007';
const RECOVERY_PREFIX='mobud-recovery-';
const LEGACY_KEYS=['mobud-beta-data-v0.000.006','mobud-beta-data-v0.000.005','vialego-beta-data-v0.000.004','mobud-beta-data-v0.000.004','vialego-data-v0.000.004','vialego-data-v0.000.003','tsumoriq-data-v0.000.001'];
const APP_CONFIG=window.MOBUD_CONFIG||window.VIALEGO_CONFIG||{};
const API=APP_CONFIG.API_BASE||'';
const GOOGLE_CLIENT_ID=APP_CONFIG.GOOGLE_CLIENT_ID||'';
const todayISO=()=>new Date().toISOString().slice(0,10);
const uid=p=>`${p}_${Date.now().toString(36)}${Math.random().toString(36).slice(2,7)}`;
const fmtMonth=d=>d.toLocaleDateString(window.MOBUD_I18N?.locale?.()||undefined,{month:'long',year:'numeric'});
const t=(text)=>window.MOBUD_I18N?.tr?.(text)||text;
const iconId=t=>({bicycle:'i-bike',ebike:'i-ebike',speed_pedelec:'i-ebike',car:'i-car',van:'i-car',motorcycle:'i-motorcycle',scooter:'i-motorcycle',public_transport:'i-train',plane:'i-plane',helicopter:'i-helicopter',walking:'i-walk',other:'i-more'})[t]||'i-more';
const iconType=t=>`<svg aria-hidden="true"><use href="#${iconId(t)}"/></svg>`
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fresh=()=>({version:VERSION,onboardingComplete:false,settings:{name:'',currency:'€',unit:'km',home1:'',home2:'',home3:'',work:'',backupFrequency:'never',reportFrequency:'never',notifyUpdates:false,commuteReminderMode:'never',dailyReminderTime:'19:00',weeklyReminderDay:6,weeklyReminderTime:'10:00',lastCommuteReminder:'',theme:'system',language:(window.MOBUD_I18N?.language||'en'),storageMode:'local',driveConnected:false,lastDriveSync:'',country:'BE',locations:[]},vehicles:[],trips:[],expenses:[],addresses:{},routeCache:{},selectedDirection:'home-work'});
function safeParse(raw){try{return raw?JSON.parse(raw):null}catch{return null}}
function normalized(data){const base=fresh(),d=data&&typeof data==='object'?data:{};return {...base,...d,settings:{...base.settings,...(d.settings||{})},vehicles:Array.isArray(d.vehicles)?d.vehicles:[],trips:Array.isArray(d.trips)?d.trips:[],expenses:Array.isArray(d.expenses)?d.expenses:[],addresses:d.addresses&&typeof d.addresses==='object'?d.addresses:{},routeCache:d.routeCache&&typeof d.routeCache==='object'?d.routeCache:{}}}
function validData(d){return d&&Array.isArray(d.trips)&&Array.isArray(d.expenses)&&Array.isArray(d.vehicles)&&d.settings&&typeof d.settings==='object'}
function snapshot(key,raw,label='migration'){if(!raw)return null;const stamp=new Date().toISOString().replace(/[:.]/g,'-');const recoveryKey=`${RECOVERY_PREFIX}${label}-${stamp}`;try{localStorage.setItem(recoveryKey,JSON.stringify({sourceKey:key,createdAt:new Date().toISOString(),raw}));return recoveryKey}catch{return null}}
function migrate(){
  const currentRaw=localStorage.getItem(KEY),current=safeParse(currentRaw);
  if(validData(current))return normalized(current);
  if(currentRaw)snapshot(KEY,currentRaw,'invalid-current');
  for(const key of LEGACY_KEYS){
    const raw=localStorage.getItem(key),old=safeParse(raw);
    if(!validData(old)&&!(old&&Array.isArray(old.trips)&&Array.isArray(old.expenses)))continue;
    snapshot(key,raw,'before-v004');
    const next=normalized(old);
    next.version=VERSION;
    next.onboardingComplete=old.onboardingComplete!==undefined?old.onboardingComplete:true;
    try{
      localStorage.setItem(KEY,JSON.stringify(next));
      const verify=safeParse(localStorage.getItem(KEY));
      if(validData(verify)&&verify.trips.length===next.trips.length&&verify.expenses.length===next.expenses.length)return verify;
    }catch{}
    return normalized(old);
  }
  return fresh();
}
let state=migrate(),viewDate=new Date(),calendarDate=new Date(),selectedDay=todayISO(),pendingAttachment={trip:null,expense:null},deferredPrompt=null,newWorker=null,tutorialIndex=0;
function applyTheme(pref=state.settings.theme||'system'){const resolved=pref==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):pref;document.documentElement.dataset.theme=resolved;document.documentElement.dataset.themePreference=pref;document.querySelector('meta[name=theme-color]')?.setAttribute('content',resolved==='light'?'#f4f4f4':'#111111')}
matchMedia('(prefers-color-scheme: light)').addEventListener?.('change',()=>{if((state.settings.theme||'system')==='system')applyTheme('system')});
function save(){const payload=JSON.stringify(state);try{localStorage.setItem(KEY,payload);const check=safeParse(localStorage.getItem(KEY));if(!validData(check)||check.trips.length!==state.trips.length||check.expenses.length!==state.expenses.length)throw new Error('Verification failed');render();return true}catch(e){toast('Save failed. Existing data was kept. Export a backup before adding more attachments.');return false}}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.classList.remove('hidden');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.add('hidden'),2600)}
function setScreen(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById('screen-'+name).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===name));if(name==='garage')renderGarage();if(name==='stats')renderStats();if(name==='calendar')renderCalendar()}
function unitDistance(km){return state.settings.unit==='mi'?`${(km*.621371).toFixed(1)} mi`:`${Number(km||0).toFixed(1)} km`}
function money(n){return `${state.settings.currency}${Number(n||0).toFixed(2)}`}
function monthItems(){const y=viewDate.getFullYear(),m=viewDate.getMonth();const ok=x=>{const d=new Date(x.date+'T12:00:00');return d.getFullYear()===y&&d.getMonth()===m};return {trips:state.trips.filter(ok),expenses:state.expenses.filter(ok)}}
function defaultVehicle(type){return state.vehicles.find(v=>v.type===type&&v.active!==false&&v.isDefault)||state.vehicles.find(v=>v.type===type&&v.active!==false)}
function vehicleById(id){return state.vehicles.find(v=>v.id===id)}
function render(){const {trips,expenses}=monthItems();currentMonthLabel.textContent=fmtMonth(viewDate);statTrips.textContent=trips.length;statKm.textContent=unitDistance(trips.reduce((s,t)=>s+Number(t.km||0),0));statCost.textContent=money(expenses.reduce((s,e)=>s+Number(e.amount||0),0));statReceipts.textContent=expenses.filter(e=>e.attachment).length;{const h=new Date().getHours();const base=h<12?t('Good morning'):h<18?t('Good afternoon'):t('Good evening');greeting.textContent=`${base}${state.settings.name?', '+state.settings.name:''}`;}renderQuick();renderRecent();renderSettings();fillVehicleSelects();window.MOBUD_I18N?.apply?.(document.body)}
function renderQuick(){
  const active=state.vehicles.filter(v=>v.active!==false);
  const usage=v=>state.trips.filter(t=>t.vehicleId===v.id).length;
  const selected=[];
  // First, keep one preferred vehicle per type.
  [...new Set(active.map(v=>v.type))].forEach(type=>{
    const same=active.filter(v=>v.type===type).sort((a,b)=>(Number(b.isDefault)-Number(a.isDefault))||(usage(b)-usage(a)));
    if(same[0]) selected.push(same[0]);
  });
  // Fill remaining places with the most-used remaining vehicles, up to five.
  active.filter(v=>!selected.includes(v)).sort((a,b)=>usage(b)-usage(a)).forEach(v=>{if(selected.length<5)selected.push(v)});
  const picks=selected.sort((a,b)=>(Number(b.isDefault)-Number(a.isDefault))||(usage(b)-usage(a))).slice(0,5);
  quickVehicles.innerHTML=picks.length?picks.map(v=>`<button class="quick-tile" data-quick-vehicle="${v.id}" title="${escapeHtml(v.name)}">${iconType(v.type)}<span>${escapeHtml(v.name)}</span><small>${String(v.type).replaceAll('_',' ')}</small></button>`).join(''):`<button class="quick-tile add-garage-tile" data-open-garage>${iconType('other')}<span>Add vehicle</span><small>Open Garage</small></button>`;
  document.querySelectorAll('[data-quick-vehicle]').forEach(b=>b.onclick=()=>quickLogVehicle(b.dataset.quickVehicle));
  document.querySelector('[data-open-garage]')?.addEventListener('click',()=>setScreen('garage'));
}
async function quickLogVehicle(vehicleId){const v=vehicleById(vehicleId);if(!v)return;const from=state.selectedDirection==='home-work'?'home1':'work',to=state.selectedDirection==='home-work'?'work':'home1';const t={id:uid('trip'),date:todayISO(),vehicleId:v.id,from,to,fromText:addressText(from),toText:addressText(to),km:0,purpose:'Commute',notes:'',createdAt:new Date().toISOString()};const coords=[state.addresses[from]?.coords,state.addresses[to]?.coords];if(coords.every(Boolean)){try{t.km=await routeDistance(coords[0],coords[1],v.type)}catch{}}state.trips.unshift(t);save();toast(`Trip saved · ${v.name} · ${t.km?t.km.toFixed(1)+' km':'edit distance'}`);editTrip(t.id)}
async function quickLog(type){const v=defaultVehicle(type);if(!v&&type!=='public_transport'){openVehicle(type);return}const from=state.selectedDirection==='home-work'?'home1':'work',to=state.selectedDirection==='home-work'?'work':'home1';const t={id:uid('trip'),date:todayISO(),vehicleId:v?.id||'',from,to,fromText:addressText(from),toText:addressText(to),km:0,purpose:'Commute',notes:'',createdAt:new Date().toISOString()};const coords=[state.addresses[from]?.coords,state.addresses[to]?.coords];if(coords.every(Boolean)){try{t.km=await routeDistance(coords[0],coords[1],v.type)}catch{}}state.trips.unshift(t);save();toast(`Trip saved · ${v?.name||'Public transport'} · ${t.km?t.km.toFixed(1)+' km':'edit distance'}`);editTrip(t.id)}
function allRows(){return [...state.trips.map(x=>({...x,kind:'trip'})),...state.expenses.map(x=>({...x,kind:'expense'}))].sort((a,b)=>(b.createdAt||b.date).localeCompare(a.createdAt||a.date))}
function renderRecent(){const rows=allRows().slice(0,8);recentList.className=rows.length?'list':'list empty-state';recentList.innerHTML=rows.length?rows.map(logHtml).join(''):'No logs yet.';bindLogButtons(recentList)}
function friendlyWhen(date){const d=new Date(date+'T12:00:00'),today=new Date();today.setHours(12,0,0,0);const diff=Math.round((today-d)/86400000);if(diff===0)return 'Today';if(diff===1)return 'Yesterday';return d.toLocaleDateString(undefined,{month:'short',day:'numeric'})}
function logHtml(x){const v=vehicleById(x.vehicleId),type=v?.type||(x.kind==='expense'?'other':'other'),attachment=x.attachment?'<span title="Attachment"> · attachment</span>':'';const title=x.kind==='trip'?friendlyWhen(x.date)+(x.createdAt?' '+new Date(x.createdAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):''):x.category;const subtitle=x.kind==='trip'?(v?.name||'No specific vehicle'):(v?.name||x.supplier||'General cost');const value=x.kind==='trip'?unitDistance(x.km):money(x.amount);return `<div class="log-row"><div class="log-icon">${iconType(type)}</div><div class="log-main"><strong>${title}</strong><small>${subtitle}${attachment}</small></div><div class="log-side"><strong>${value}</strong><div class="log-actions"><button class="ghost" data-edit-${x.kind}="${x.id}">Edit</button><button class="danger" data-delete-${x.kind}="${x.id}">Delete</button></div></div></div>`}
function bindLogButtons(root=document){root.querySelectorAll('[data-edit-trip]').forEach(b=>b.onclick=()=>editTrip(b.dataset.editTrip));root.querySelectorAll('[data-edit-expense]').forEach(b=>b.onclick=()=>editExpense(b.dataset.editExpense));root.querySelectorAll('[data-delete-trip]').forEach(b=>b.onclick=()=>deleteLog('trip',b.dataset.deleteTrip));root.querySelectorAll('[data-delete-expense]').forEach(b=>b.onclick=()=>deleteLog('expense',b.dataset.deleteExpense))}
function deleteLog(kind,id){if(!confirm('Delete this record?'))return;if(!confirm('Are you sure? This cannot be undone.'))return;state[kind==='trip'?'trips':'expenses']=state[kind==='trip'?'trips':'expenses'].filter(x=>x.id!==id);save();renderCalendar()}
function fillVehicleSelects(){const opts=['<option value="">No specific vehicle</option>',...state.vehicles.filter(v=>v.active!==false).map(v=>`<option value="${v.id}">${iconType(v.type)} ${v.name}${v.isDefault?' · default':''}</option>`)].join('');tripVehicle.innerHTML=opts;expenseVehicle.innerHTML=opts}
function allLocations(){
  const base=[
    {id:'home1',kind:'home',label:state.settings.homeLabel||'Home',address:state.settings.home1||''},
    {id:'work',kind:'work',label:state.settings.workLabel||'Work',address:state.settings.work||''}
  ];
  return base.concat(Array.isArray(state.settings.locations)?state.settings.locations:[]);
}
function fillLocations(){
  const locations=allLocations();
  const opts=[...locations.map(l=>[l.id,l.label||l.address||l.id]),['other','Other']];
  tripFrom.innerHTML=opts.map(([k,n])=>`<option value="${k}">${escapeHtml(n)}</option>`).join('');
  tripTo.innerHTML=tripFrom.innerHTML;
}
function addressText(k){
  if(k==='other')return 'Other';
  const loc=allLocations().find(l=>l.id===k);
  return loc?.address||loc?.label||k;
}
function editTrip(id){const t=state.trips.find(x=>x.id===id);if(!t)return;setScreen('log');document.querySelector('[data-tab="trip"]').click();tripEditId.value=t.id;tripFormTitle.textContent='Edit trip';tripDate.value=t.date;tripVehicle.value=t.vehicleId||'';fillLocations();tripFrom.value=t.from||'home1';tripTo.value=t.to||'work';tripKm.value=t.km||0;tripPurpose.value=t.purpose||'Commute';tripNotes.value=t.notes||'';pendingAttachment.trip=t.attachment||null;showAttachment('trip');cancelTripEdit.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function editExpense(id){const x=state.expenses.find(e=>e.id===id);if(!x)return;setScreen('log');document.querySelector('[data-tab="expense"]').click();expenseEditId.value=x.id;expenseFormTitle.textContent='Edit cost';expenseDate.value=x.date;expenseVehicle.value=x.vehicleId||'';expenseCategory.value=x.category;expenseAmount.value=x.amount;expenseSupplier.value=x.supplier||'';expenseOdometer.value=x.odometer||'';expenseNotes.value=x.notes||'';pendingAttachment.expense=x.attachment||null;showAttachment('expense');cancelExpenseEdit.classList.remove('hidden')}
function resetTrip(){tripForm.reset();tripEditId.value='';tripFormTitle.textContent='Log trip';tripDate.value=todayISO();pendingAttachment.trip=null;showAttachment('trip');cancelTripEdit.classList.add('hidden');fillLocations()}
function resetExpense(){expenseForm.reset();expenseEditId.value='';expenseFormTitle.textContent='Cost / receipt';expenseDate.value=todayISO();pendingAttachment.expense=null;showAttachment('expense');cancelExpenseEdit.classList.add('hidden')}
async function fileData(file){if(!file)return null;if(file.size>4_000_000)throw new Error('File too large');return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res({name:file.name,type:file.type,data:r.result,date:new Date().toISOString()});r.onerror=rej;r.readAsDataURL(file)})}
function showAttachment(kind){const box=document.getElementById(kind+'AttachmentInfo'),a=pendingAttachment[kind];box.classList.toggle('hidden',!a);box.innerHTML=a?`📎 ${a.name} <button type="button" class="ghost small" id="remove_${kind}_att">Remove</button>`:'';if(a)document.getElementById(`remove_${kind}_att`).onclick=()=>{pendingAttachment[kind]=null;showAttachment(kind)}}
function vehicleDistance(v){return state.trips.filter(t=>t.vehicleId===v.id).reduce((sum,t)=>sum+Number(t.km||0),0)}
function maintenanceTimeline(v){
  const current=Math.max(vehicleDistance(v),...state.expenses.filter(e=>e.vehicleId===v.id).map(e=>Number(e.odometer||0)),0);
  const maintenance=state.expenses.filter(e=>e.vehicleId===v.id&&e.category==='Maintenance'&&Number(e.odometer||0)>0).sort((a,b)=>a.odometer-b.odometer);
  const last=maintenance.at(-1);const interval=Number(v.maintenanceKm||0);const due=interval?(Number(last?.odometer||0)+interval):0;
  const max=Math.max(current,due,1);const p=n=>Math.min(100,Math.max(0,(Number(n||0)/max)*100));
  return `<div class="maintenance-timeline"><div class="timeline-track"></div><span class="timeline-point start" style="left:0%"><b>0</b></span>${maintenance.map(m=>`<span class="timeline-point maintenance" style="left:${p(m.odometer)}%" title="Maintenance ${m.date}"><b>${Number(m.odometer).toFixed(0)} km</b><i>●</i></span>`).join('')}<span class="timeline-point current" style="left:${p(current)}%"><b>${current.toFixed(0)} km current</b><i>●</i></span>${due>current?`<span class="timeline-point due" style="left:${p(due)}%"><b>${due.toFixed(0)} km maintenance</b><i>●</i></span>`:''}</div>`
}
function renderGarage(){const typeFilter=document.getElementById('garageTypeFilter')?.value||'all',powerFilter=document.getElementById('garagePowertrainFilter')?.value||'all';const list=state.vehicles.filter(v=>(typeFilter==='all'||v.type===typeFilter)&&(powerFilter==='all'||(v.powertrain||'not_applicable')===powerFilter));if(!list.length){garageList.innerHTML='<div class="card empty-state">No matching vehicles.</div>';return}garageList.innerHTML=list.map(v=>{const trips=state.trips.filter(t=>t.vehicleId===v.id),logs=state.expenses.filter(e=>e.vehicleId===v.id);const title=[v.brand,v.model].filter(Boolean).join(' ')||v.name;return `<div class="card garage-card"><div class="section-head"><div class="vehicle-title"><span class="vehicle-icon">${iconType(v.type)}</span><div><h3>${title}</h3><strong>${v.name}</strong><p class="muted">${String(v.type).replaceAll('_',' ')} · ${String(v.powertrain||'not_applicable').replaceAll('_',' ')}</p>${v.isDefault?'<span class="default-badge">DEFAULT</span>':''}</div></div><div class="log-actions"><button class="ghost" data-edit-vehicle="${v.id}">Edit</button><button class="ghost" data-archive-vehicle="${v.id}">${v.active===false?'Restore':'Archive'}</button></div></div><div class="vehicle-meta"><div><small>Distance logged</small>${unitDistance(trips.reduce((s,t)=>s+Number(t.km||0),0))}</div><div><small>Tickets & logs</small>${logs.length}</div><div><small>Total cost</small>${money(logs.reduce((s,e)=>s+Number(e.amount||0),0))}</div><div><small>Status</small>${v.active===false?'Archived':'Active'}</div></div>${['bicycle','ebike','speed_pedelec','car','van','motorcycle','scooter'].includes(v.type)?maintenanceTimeline(v):''}${v.leasePartner?`<p>Lease partner: ${link(v.leasePartner,v.leaseUrl)}</p>`:''}${v.maintenanceProvider?`<p>Maintenance: ${link(v.maintenanceProvider,v.maintenanceUrl)}</p>`:''}${v.insurance?`<p>Insurance: ${v.insurance}</p>`:''}<button class="secondary small" data-vehicle-logs="${v.id}">See all logs for this vehicle</button></div>`}).join('');document.querySelectorAll('[data-edit-vehicle]').forEach(b=>b.onclick=()=>openVehicle(null,b.dataset.editVehicle));document.querySelectorAll('[data-archive-vehicle]').forEach(b=>b.onclick=()=>archiveVehicle(b.dataset.archiveVehicle));document.querySelectorAll('[data-vehicle-logs]').forEach(b=>b.onclick=()=>showVehicleLogs(b.dataset.vehicleLogs))}
function link(label,url){return url?`<a href="${url}" target="_blank" rel="noopener">${label}</a>`:label}

const POWERTRAIN_OPTIONS={bicycle:[['not_applicable','Not applicable']],ebike:[['electric','Electric']],speed_pedelec:[['electric','Electric']],scooter:[['electric','Electric'],['petrol','Petrol']],motorcycle:[['electric','Electric'],['petrol','Petrol']],car:[['electric','Electric'],['petrol','Petrol'],['diesel','Diesel'],['hybrid_petrol','Hybrid petrol'],['hybrid_diesel','Hybrid diesel'],['plug_in_hybrid','Plug-in hybrid'],['lpg','LPG'],['cng','CNG'],['hydrogen','Hydrogen']],van:[['electric','Electric'],['petrol','Petrol'],['diesel','Diesel'],['hybrid_petrol','Hybrid petrol'],['plug_in_hybrid','Plug-in hybrid'],['lpg','LPG'],['cng','CNG'],['hydrogen','Hydrogen']],plane:[['kerosene','Kerosene'],['electric','Electric'],['other','Other']],helicopter:[['kerosene','Kerosene'],['electric','Electric'],['other','Other']],other:[['not_applicable','Not applicable'],['electric','Electric'],['petrol','Petrol'],['diesel','Diesel'],['other','Other']]};
function updatePowertrainOptions(value){const options=POWERTRAIN_OPTIONS[value]||POWERTRAIN_OPTIONS.other,old=vehiclePowertrain.value;vehiclePowertrain.innerHTML=options.map(([v,l])=>`<option value="${v}">${l}</option>`).join('');if(options.some(([v])=>v===old))vehiclePowertrain.value=old}
function openVehicle(type='bicycle',id=''){vehicleForm.reset();vehicleId.value='';vehicleFormTitle.textContent=id?'Edit vehicle':'Add vehicle';if(id){const v=vehicleById(id);Object.entries({vehicleId:v?.id||'',vehicleType:v.type,vehicleName:v.name,vehicleBrand:v.brand,vehicleModel:v.model,vehiclePowertrain:v.powertrain||'not_applicable',vehicleBoughtFrom:v.boughtFrom,vehicleSellerUrl:v.sellerUrl,vehicleLeasePartner:v.leasePartner,vehicleLeaseUrl:v.leaseUrl,vehicleLeaseStart:v.leaseStart,vehicleLeaseEnd:v.leaseEnd,vehicleMaintenanceProvider:v.maintenanceProvider,vehicleMaintenanceUrl:v.maintenanceUrl,vehicleMaintenanceContact:v.maintenanceContact,vehicleMaintenanceAddress:v.maintenanceAddress,vehicleInsurance:v.insurance,vehicleInsuranceUrl:v.insuranceUrl,vehicleInsurancePhone:v.insurancePhone,vehicleInsuranceAddress:v.insuranceAddress,vehicleSellerPhone:v.sellerPhone,vehicleSellerAddress:v.sellerAddress,vehicleLeasePhone:v.leasePhone,vehicleLeaseAddress:v.leaseAddress,vehicleMaintenanceMonths:v.maintenanceMonths,vehicleMaintenanceKm:v.maintenanceKm}).forEach(([k,val])=>{document.getElementById(k).value=val||''});vehicleDefault.checked=!!v.isDefault;updatePowertrainOptions(v.type);vehiclePowertrain.value=v.powertrain||vehiclePowertrain.value}else{vehicleType.value=type||'bicycle';updatePowertrainOptions(vehicleType.value)}vehicleModal.classList.remove('hidden')}
function archiveVehicle(id){const v=vehicleById(id);if(!v)return;if(v.isDefault&&v.active!==false&&!confirm('This is the default vehicle. Archive it and choose a new default later?'))return;v.active=v.active===false;save();renderGarage()}
function showVehicleLogs(id){selectedDay=todayISO();setScreen('calendar');const rows=allRows().filter(x=>x.vehicleId===id);selectedDayTitle.textContent=`Logs for ${vehicleById(id)?.name||'vehicle'}`;dayLogs.innerHTML=rows.length?rows.map(logHtml).join(''):'No logs.';bindLogButtons(dayLogs)}
function renderStats(){
  const totalKm=state.trips.reduce((s,t)=>s+Number(t.km||0),0);
  const totalCost=state.expenses.reduce((s,e)=>s+Number(e.amount||0),0);
  const receipts=state.expenses.filter(e=>e.attachment).length;
  const byVehicle=state.vehicles.map(v=>({
    v,
    km:state.trips.filter(t=>t.vehicleId===v.id).reduce((s,t)=>s+Number(t.km||0),0)
  })).filter(x=>x.km>0).sort((a,b)=>b.km-a.km);

  const palette=['#ff9d1c','#ffc14d','#f07818','#d9a441','#f4f4f4','#9b9b9f','#6f7075','#45464b'];
  let cursor=0;
  const gradientParts=byVehicle.map((x,i)=>{
    const percentage=totalKm?x.km/totalKm*100:0;
    const from=cursor;
    cursor+=percentage;
    return `${palette[i%palette.length]} ${from.toFixed(2)}% ${cursor.toFixed(2)}%`;
  });
  const usageChart=byVehicle.length?`<div class="usage-mix-layout"><div class="usage-donut" role="img" aria-label="Share of logged distance by vehicle" style="--usage-gradient:conic-gradient(${gradientParts.join(',')})"><div><strong>${byVehicle.length}</strong><span>vehicles</span></div></div><div class="usage-legend">${byVehicle.map((x,i)=>{const percentage=totalKm?x.km/totalKm*100:0;return `<div class="usage-legend-row"><span class="usage-dot" style="background:${palette[i%palette.length]}"></span><span class="usage-name">${escapeHtml(x.v.name)}</span><strong>${percentage.toFixed(1)}%</strong></div>`}).join('')}</div></div>`:'<p class="muted">Log trips with Garage vehicles to see your mobility mix.</p>';

  const cyclingTypes=['bicycle','ebike','speed_pedelec'];
  const cyclingKm=state.trips.filter(t=>cyclingTypes.includes(vehicleById(t.vehicleId)?.type)).reduce((s,t)=>s+Number(t.km||0),0);
  const estimatedCo2Saved=cyclingKm*0.17;

  statsContent.innerHTML=`
    <div class="card usage-mix-card">
      <div class="section-head"><div><h3>Vehicle usage mix</h3><p class="muted">Share of your logged distance</p></div></div>
      ${usageChart}
    </div>
    <div class="stats-kpi-grid">
      <div class="card stat-summary-row"><span>Total trips</span><strong>${state.trips.length}</strong></div>
      <div class="card stat-summary-row"><span>Total distance</span><strong>${unitDistance(totalKm)}</strong></div>
      <div class="card stat-summary-row"><span>Total costs</span><strong>${money(totalCost)}</strong></div>
      <div class="card stat-summary-row"><span>Receipts</span><strong>${receipts}</strong></div>
    </div>
    <div class="card">
      <h3>Distance per vehicle</h3>
      <div class="vehicle-distance-list">${byVehicle.map(x=>`<div class="vehicle-distance-row"><span class="vehicle-distance-icon">${iconType(x.v.type)}</span><span class="vehicle-distance-name">${escapeHtml(x.v.name)}</span><strong>${unitDistance(x.km)}</strong></div>`).join('')||'<p class="muted">No distance yet.</p>'}</div>
    </div>
    <div class="card impact-card">
      <h3>Estimated impact</h3>
      <div class="impact-row"><span>Cycling distance</span><strong>${unitDistance(cyclingKm)}</strong></div>
      <div class="impact-row"><span>Estimated CO₂ avoided</span><strong>${estimatedCo2Saved.toFixed(1)} kg</strong></div>
      <p class="muted">Estimated against an avoided average car journey. Actual savings vary by vehicle, energy source and route.</p>
    </div>`;
}
function renderCalendar(){calendarTitle.textContent=fmtMonth(calendarDate);const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,days=new Date(y,m+1,0).getDate(),counts={};allRows().forEach(x=>counts[x.date]=(counts[x.date]||0)+1);let html='';for(let i=0;i<first;i++)html+='<span></span>';for(let d=1;d<=days;d++){const iso=`${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;html+=`<button class="cal-day ${counts[iso]?'filled':''} ${iso===selectedDay?'selected':''} ${iso===todayISO()?'today':''}" data-day="${iso}"><span>${d}</span>${counts[iso]?`<small>${counts[iso]}</small>`:''}</button>`}calendarGrid.innerHTML=html;document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;renderCalendar()});selectedDayTitle.textContent=new Date(selectedDay+'T12:00:00').toLocaleDateString(undefined,{weekday:'long',day:'numeric',month:'long'});const rows=allRows().filter(x=>x.date===selectedDay);dayLogs.innerHTML=rows.length?rows.map(logHtml).join(''):'No registrations on this day.';bindLogButtons(dayLogs)}
function renderSettings(){settingName.value=state.settings.name||'';settingLanguage.value=state.settings.language||window.MOBUD_I18N?.language||'en';settingCurrency.value=state.settings.currency||'€';settingUnit.value=state.settings.unit||'km';settingTheme.value=state.settings.theme||'system';commuteReminderMode.value=state.settings.commuteReminderMode||'never';dailyReminderTime.value=state.settings.dailyReminderTime||'19:00';weeklyReminderDay.value=String(state.settings.weeklyReminderDay??6);weeklyReminderTime.value=state.settings.weeklyReminderTime||'10:00';backupFrequency.value=state.settings.backupFrequency||'never';reportFrequency.value=state.settings.reportFrequency||'never';notifyUpdates.checked=!!state.settings.notifyUpdates;storageStatus.textContent=state.settings.driveConnected?`Google Drive connected · last sync ${state.settings.lastDriveSync||'never'}`:'Data is stored locally on this device.';linkDrive.classList.toggle('hidden',state.settings.driveConnected);syncDrive.classList.toggle('hidden',!state.settings.driveConnected);disconnectDrive.classList.toggle('hidden',!state.settings.driveConnected);addressFields.innerHTML=['home1','home2','home3','work'].map(k=>`<label>${({home1:'Home 1',home2:'Home 2',home3:'Home 3',work:'Work'})[k]}<input data-address="${k}" value="${state.settings[k]||''}" placeholder="Enter and select an address"><div class="suggestions" id="suggest_${k}"></div></label>`).join('');document.querySelectorAll('[data-address]').forEach(inp=>{let timer;inp.oninput=()=>{clearTimeout(timer);timer=setTimeout(()=>searchAddress(inp.dataset.address,inp.value),450)}});renderFaq()}
async function searchAddress(key,text){const box=document.getElementById('suggest_'+key);if(text.trim().length<3){box.innerHTML='';return}try{const r=await fetch(`${API}/geocode?text=${encodeURIComponent(text)}`,{cache:'no-store'});if(!r.ok)throw new Error(r.status);const j=await r.json();box.innerHTML=(j.features||[]).slice(0,5).map((f,i)=>`<button type="button" class="ghost small" data-suggestion="${key}" data-index="${i}">${f.properties.label}</button>`).join('');box._features=j.features||[];box.querySelectorAll('[data-suggestion]').forEach(b=>b.onclick=()=>{const f=box._features[Number(b.dataset.index)];state.settings[key]=f.properties.label;state.addresses[key]={label:f.properties.label,coords:f.geometry.coordinates};save()})}catch(e){box.innerHTML='<small class="muted">Address search unavailable; manual entry remains possible.</small>'}}
function profile(type){return ['bicycle','ebike','speed_pedelec'].includes(type)?'cycling-regular':type==='walking'?'foot-walking':'driving-car'}
async function routeDistance(a,b,type){const cacheKey=[profile(type),...a,...b].join('|');if(state.routeCache[cacheKey])return state.routeCache[cacheKey];const r=await fetch(`${API}/route`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({profile:profile(type),coordinates:[a,b]})});if(!r.ok)throw new Error(r.status);const j=await r.json();const km=j.features?.[0]?.properties?.summary?.distance/1000;if(!km)throw new Error('No route');state.routeCache[cacheKey]=km;save();return km}
function renderFaq(){const items=[['How do I add a vehicle?','Open Garage and tap Add vehicle. The first vehicle of a type becomes the default.','garage'],['How do I attach a ticket or bill?','Open Log, choose Trip or Cost, then Choose file or Take photo. Keep the original document.','log'],['Can I discard the original receipt?','No. Keep the legally valid paper or native electronic original for the applicable retention period. MoBud copies are administrative aids only.'],['Where is my data stored?','Locally by default. Optional Google Drive backup remains in your own Google account. MoBud does not operate a central trip database.'],['How do I use multiple devices?','Link the same Google Drive account on each device, then restore or sync the same backup.'],['How do commute reminders work?','Choose daily or weekly in Setup. The beta checks reminders whenever MoBud is open; reliable closed-app notifications require the future push service.'],['Does MoBud determine tax deductibility?','No. Consult your accountant or tax adviser. MoBud only organises records and estimates.']];faqList.innerHTML=items.map((x,i)=>`<div class="faq-item"><button data-faq="${i}">${x[0]}</button><div class="faq-answer hidden" id="faq_${i}">${x[1]} ${x[2]?`<button class="ghost small" data-tutorial-start="${x[2]}">Show tutorial</button>`:''}</div></div>`).join('');document.querySelectorAll('[data-faq]').forEach(b=>b.onclick=()=>document.getElementById('faq_'+b.dataset.faq).classList.toggle('hidden'));document.querySelectorAll('[data-tutorial-start]').forEach(b=>b.onclick=()=>startTutorial(b.dataset.tutorialStart))}
const tutorialSteps=[
{id:'quick-commute',title:'Quick commute',text:'Choose the direction for this commute.',screen:'dashboard',target:'[data-tutorial="commute-panel"]'},
{id:'quick-log',title:'Choose your vehicle',text:'Swipe horizontally and tap one of your Garage vehicles. Defaults or most-used vehicles are shown.',screen:'dashboard',target:'[data-tutorial="quick-log"]'},
{id:'open-log',title:'Add or adjust a log',text:'Use the central button to add a trip, cost or receipt.',screen:'dashboard',target:'[data-tutorial="nav-log"]'},
{id:'trip-form',title:'Review a trip',text:'Adjust distance, date, vehicle or attachment before saving.',screen:'log',target:'[data-tutorial="trip-form"]',action:()=>document.querySelector('[data-tab="trip"]')?.click()},
{id:'expense-form',title:'Add a ticket or bill',text:'Choose a file or take a photo. Keep the legally valid original.',screen:'log',target:'[data-tutorial="expense-form"]',action:()=>document.querySelector('[data-tab="expense"]')?.click()},
{id:'garage-nav',title:'Open your Garage',text:'Use Garage to add, edit and maintain your vehicles.',screen:'dashboard',target:'[data-tutorial="nav-garage"]'},
{id:'garage',title:'Manage vehicles',text:'Filter, edit, archive and choose default vehicles here.',screen:'garage',target:'[data-tutorial="garage-screen"]'},
{id:'stats-nav',title:'Open Reports',text:'Use Reports for distance, costs, receipts and vehicle totals.',screen:'dashboard',target:'[data-tutorial="nav-stats"]'},
{id:'help-nav',title:'More and FAQ',text:'Settings, FAQ, tutorials and feedback are under More.',screen:'dashboard',target:'[data-tutorial="nav-settings"]'}]
function startTutorial(id){tutorialIndex=Math.max(0,tutorialSteps.findIndex(s=>s.id===id||s.title.toLowerCase().includes(String(id||'').toLowerCase())));tutorial.classList.remove('hidden');showTutorial()}
const waitForElement=(selector,timeout=1600)=>new Promise(resolve=>{const start=performance.now();(function tick(){const el=document.querySelector(selector);if(el)return resolve(el);if(performance.now()-start>timeout)return resolve(null);requestAnimationFrame(tick)})()});
async function showTutorial(){const step=tutorialSteps[tutorialIndex];tutorialCount.textContent=`${tutorialIndex+1} / ${tutorialSteps.length}`;tutorialTitle.textContent=step.title;tutorialText.textContent=step.text;tutorialNext.textContent=tutorialIndex===tutorialSteps.length-1?'Have fun':'Next';setScreen(step.screen);step.action?.();const el=await waitForElement(step.target);if(!el){tutorialIndex++;if(tutorialIndex<tutorialSteps.length)return showTutorial();tutorial.classList.add('hidden');return}el.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});await new Promise(r=>setTimeout(r,360));requestAnimationFrame(()=>requestAnimationFrame(()=>positionTutorial(el)))}
function positionTutorial(el){const r=el.getBoundingClientRect(),pad=7;const left=Math.max(6,r.left-pad),top=Math.max(6,r.top-pad),width=Math.min(innerWidth-left-6,r.width+pad*2),height=Math.min(innerHeight-top-6,r.height+pad*2);tutorialSpot.style.cssText=`left:${left}px;top:${top}px;width:${width}px;height:${height}px`}
window.addEventListener('resize',()=>{if(!tutorial.classList.contains('hidden')){const step=tutorialSteps[tutorialIndex],el=document.querySelector(step?.target);if(el)positionTutorial(el)}});
function finishOnboardingFlow(){state.onboardingComplete=true;state.settings.name=onboardName.value.trim();state.settings.language=onboardLanguage.value||window.MOBUD_I18N?.language||'en';window.MOBUD_I18N?.setLanguage?.(state.settings.language);state.settings.storageMode=document.querySelector('[name=storageChoice]:checked').value;state.settings.commuteReminderMode=onboardCommuteReminder.value;state.settings.dailyReminderTime='19:00';state.settings.weeklyReminderDay=6;state.settings.weeklyReminderTime='10:00';state.settings.backupFrequency=onboardBackup.value;state.settings.reportFrequency=onboardReport.value;state.settings.notifyUpdates=onboardNotify.checked;save();onboarding.classList.add('hidden');if(state.settings.storageMode==='drive')linkGoogleDrive();setTimeout(()=>{if(confirm('Want a quick MoBud tutorial?'))startTutorial()},200)}
const DRIVE_BACKUP_NAME='mobud-backup.json';
async function driveFetch(url,options={}){const token=sessionStorage.getItem('mobudGoogleToken');if(!token)throw new Error('NO_TOKEN');const headers=new Headers(options.headers||{});headers.set('Authorization',`Bearer ${token}`);const response=await fetch(url,{...options,headers});if(response.status===401)sessionStorage.removeItem('mobudGoogleToken');return response}
async function findDriveBackup(){const q=encodeURIComponent(`name='${DRIVE_BACKUP_NAME}' and 'appDataFolder' in parents and trashed=false`);const r=await driveFetch(`https://www.googleapis.com/drive/v3/files?spaces=appDataFolder&q=${q}&fields=files(id,name,modifiedTime)&pageSize=10`);if(!r.ok)throw new Error(`Drive list failed (${r.status})`);const j=await r.json();return (j.files||[]).sort((a,b)=>String(b.modifiedTime).localeCompare(String(a.modifiedTime)))[0]||null}
async function downloadDriveBackup(fileId){const r=await driveFetch(`https://www.googleapis.com/drive/v3/files/${encodeURIComponent(fileId)}?alt=media`);if(!r.ok)throw new Error(`Drive download failed (${r.status})`);const data=normalized(await r.json());if(!validData(data))throw new Error('Invalid Drive backup');return data}
async function uploadDriveBackup(existingId=''){const metadata={name:DRIVE_BACKUP_NAME,mimeType:'application/json'};if(!existingId)metadata.parents=['appDataFolder'];const boundary='mobud_'+Math.random().toString(36).slice(2);const body=`--${boundary}\r\nContent-Type: application/json; charset=UTF-8\r\n\r\n${JSON.stringify(metadata)}\r\n--${boundary}\r\nContent-Type: application/json\r\n\r\n${JSON.stringify(buildBackupPayload())}\r\n--${boundary}--`;const endpoint=existingId?`https://www.googleapis.com/upload/drive/v3/files/${encodeURIComponent(existingId)}?uploadType=multipart`:'https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart';const r=await driveFetch(endpoint,{method:existingId?'PATCH':'POST',headers:{'Content-Type':`multipart/related; boundary=${boundary}`},body});if(!r.ok)throw new Error(`Drive upload failed (${r.status})`);return r.json()}
async function linkGoogleDrive(){if(!GOOGLE_CLIENT_ID){toast('Add the Google OAuth Client ID to config.js first.');return}if(!window.google?.accounts?.oauth2){toast('Google sign-in is not ready yet. Reload and try again.');return}const client=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CLIENT_ID,scope:'https://www.googleapis.com/auth/drive.appdata',callback:async token=>{if(token.error){toast('Google Drive connection was cancelled.');return}sessionStorage.setItem('mobudGoogleToken',token.access_token);state.settings.driveConnected=true;state.settings.storageMode='drive';save();await syncToDrive(true)}});client.requestAccessToken({prompt:'consent'})}
async function syncToDrive(firstConnection=false){const token=sessionStorage.getItem('mobudGoogleToken');if(!token){linkGoogleDrive();return}try{toast('Checking Google Drive…');const existing=await findDriveBackup();if(existing&&firstConnection){const restore=confirm('A MoBud backup already exists in this Google Drive. Press OK to restore it on this device. Press Cancel to keep this device and replace the Drive backup.');if(restore){const remote=await downloadDriveBackup(existing.id);snapshot(KEY,JSON.stringify(state),'before-drive-restore');state=remote;state.settings.driveConnected=true;state.settings.storageMode='drive';state.settings.lastDriveSync=new Date().toLocaleString();save();toast(`Drive backup restored · ${state.vehicles.length} vehicle(s)`);return}}await uploadDriveBackup(existing?.id||'');state.settings.lastDriveSync=new Date().toLocaleString();state.settings.driveConnected=true;state.settings.storageMode='drive';save();toast('Google Drive backup updated.')}catch(error){console.error(error);toast('Google Drive sync failed. Your local data was kept.')}}
function openFeedback(type){feedbackForm.reset();feedbackType.value=type;feedbackTitle.textContent=type==='bug'?'Report bug':'Send request';feedbackModal.classList.remove('hidden')}
function feedbackPayload(){return {type:feedbackType.value,title:feedbackSubject.value,description:feedbackDescription.value,severity:feedbackSeverity.value,email:feedbackEmail.value,mayContact:feedbackContact.checked,version:VERSION,platform:navigator.platform,installed:matchMedia('(display-mode: standalone)').matches,online:navigator.onLine}}

function reminderKeyForNow(){const n=new Date(),mode=state.settings.commuteReminderMode;if(mode==='daily'){const [h,m]=(state.settings.dailyReminderTime||'19:00').split(':').map(Number);if(n.getHours()>h||(n.getHours()===h&&n.getMinutes()>=m))return `daily-${todayISO()}`}if(mode==='weekly'&&n.getDay()===Number(state.settings.weeklyReminderDay??6)){const [h,m]=(state.settings.weeklyReminderTime||'10:00').split(':').map(Number);if(n.getHours()>h||(n.getHours()===h&&n.getMinutes()>=m))return `weekly-${todayISO()}`}return ''}
function checkCommuteReminder(){const key=reminderKeyForNow();if(!key||state.settings.lastCommuteReminder===key)return;state.settings.lastCommuteReminder=key;save();const msg=state.settings.commuteReminderMode==='weekly'?'Review and complete your commutes from the past week.':'Remember to log today’s commute.';toast(msg);if(Notification.permission==='granted')new Notification('MoBud reminder',{body:msg,icon:'icon-192-v005.png'})}
async function requestReminderPermission(){if(commuteReminderMode.value==='never'||!('Notification'in window))return;if(Notification.permission==='default')await Notification.requestPermission()}
// events
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setScreen(b.dataset.screen));document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>setScreen(b.dataset.jump));document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');tripForm.classList.toggle('active-form',b.dataset.tab==='trip');expenseForm.classList.toggle('active-form',b.dataset.tab==='expense')});
dirHomeWork.onclick=()=>{state.selectedDirection='home-work';dirHomeWork.classList.add('active');dirWorkHome.classList.remove('active')};dirWorkHome.onclick=()=>{state.selectedDirection='work-home';dirWorkHome.classList.add('active');dirHomeWork.classList.remove('active')};
prevMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};nextMonth.onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};viewAllLogs.onclick=()=>setScreen('calendar');calPrev.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()-1);renderCalendar()};calNext.onclick=()=>{calendarDate.setMonth(calendarDate.getMonth()+1);renderCalendar()};addVehicleBtn.onclick=()=>openVehicle();garageTypeFilter.onchange=renderGarage;garagePowertrainFilter.onchange=renderGarage;cancelVehicle.onclick=()=>vehicleModal.classList.add('hidden');
vehicleForm.onsubmit=e=>{e.preventDefault();const id=vehicleId.value||uid('vehicle');const data={id,type:vehicleType.value,powertrain:vehiclePowertrain.value,name:vehicleName.value.trim(),brand:vehicleBrand.value.trim(),model:vehicleModel.value.trim(),isDefault:vehicleDefault.checked,boughtFrom:vehicleBoughtFrom.value,sellerUrl:vehicleSellerUrl.value,leasePartner:vehicleLeasePartner.value,leaseUrl:vehicleLeaseUrl.value,leaseStart:vehicleLeaseStart.value,leaseEnd:vehicleLeaseEnd.value,maintenanceProvider:vehicleMaintenanceProvider.value,maintenanceUrl:vehicleMaintenanceUrl.value,maintenanceContact:vehicleMaintenanceContact.value,maintenanceAddress:vehicleMaintenanceAddress.value,insurance:vehicleInsurance.value,insuranceUrl:vehicleInsuranceUrl.value,insurancePhone:vehicleInsurancePhone.value,insuranceAddress:vehicleInsuranceAddress.value,sellerPhone:vehicleSellerPhone.value,sellerAddress:vehicleSellerAddress.value,leasePhone:vehicleLeasePhone.value,leaseAddress:vehicleLeaseAddress.value,maintenanceMonths:Number(vehicleMaintenanceMonths.value||0),maintenanceKm:Number(vehicleMaintenanceKm.value||0),active:true};if(!state.vehicles.some(v=>v.type===data.type&&v.active!==false))data.isDefault=true;if(data.isDefault)state.vehicles.forEach(v=>{if(v.type===data.type)v.isDefault=false});const i=state.vehicles.findIndex(v=>v.id===id);if(i>=0)data.active=state.vehicles[i].active; i>=0?state.vehicles.splice(i,1,data):state.vehicles.push(data);save();vehicleModal.classList.add('hidden');renderGarage()};
tripForm.onsubmit=e=>{e.preventDefault();const id=tripEditId.value||uid('trip'),old=state.trips.find(x=>x.id===id);const row={id,date:tripDate.value,vehicleId:tripVehicle.value,from:tripFrom.value,to:tripTo.value,fromText:tripFrom.value==='other'?tripFromOther.value:addressText(tripFrom.value),toText:tripTo.value==='other'?tripToOther.value:addressText(tripTo.value),km:Number(tripKm.value||0),purpose:tripPurpose.value,notes:tripNotes.value,attachment:pendingAttachment.trip||null,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const i=state.trips.findIndex(x=>x.id===id);i>=0?state.trips.splice(i,1,row):state.trips.unshift(row);save();resetTrip();toast('Trip saved')};
expenseForm.onsubmit=e=>{e.preventDefault();const id=expenseEditId.value||uid('expense'),old=state.expenses.find(x=>x.id===id);const row={id,date:expenseDate.value,vehicleId:expenseVehicle.value,category:expenseCategory.value,amount:Number(expenseAmount.value||0),supplier:expenseSupplier.value,odometer:Number(expenseOdometer.value||0),notes:expenseNotes.value,attachment:pendingAttachment.expense||null,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};const i=state.expenses.findIndex(x=>x.id===id);i>=0?state.expenses.splice(i,1,row):state.expenses.unshift(row);save();resetExpense();toast('Cost saved')};
[['tripFile','trip'],['tripCamera','trip'],['expenseFile','expense'],['expenseCamera','expense']].forEach(([id,k])=>document.getElementById(id).onchange=async e=>{try{pendingAttachment[k]=await fileData(e.target.files[0]);showAttachment(k)}catch(err){toast(err.message)}});
tripFrom.onchange=()=>tripFromOtherWrap.classList.toggle('hidden',tripFrom.value!=='other');tripTo.onchange=()=>tripToOtherWrap.classList.toggle('hidden',tripTo.value!=='other');swapTrip.onclick=()=>{const a=tripFrom.value;tripFrom.value=tripTo.value;tripTo.value=a};calcRoute.onclick=async()=>{const a=state.addresses[tripFrom.value]?.coords,b=state.addresses[tripTo.value]?.coords,v=vehicleById(tripVehicle.value);if(!a||!b){toast('Select saved addresses with coordinates first.');return}try{calcRoute.textContent='Calculating…';tripKm.value=(await routeDistance(a,b,v?.type||'car')).toFixed(1);toast('Route distance calculated')}catch{toast('Route unavailable; enter distance manually.')}finally{calcRoute.textContent='Calculate route'}};
cancelTripEdit.onclick=resetTrip;cancelExpenseEdit.onclick=resetExpense;commuteReminderMode.onchange=requestReminderPermission;
function buildBackupPayload(){return {...state,settings:{...state.settings},vehicles:[...state.vehicles],trips:[...state.trips],expenses:[...state.expenses],exportedAt:new Date().toISOString(),exportVersion:VERSION}}
function downloadBackup(reason='manual'){const payload=buildBackupPayload();const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`mobud-backup-${reason}-${todayISO()}.json`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);return payload}
exportJson.onclick=()=>downloadBackup('manual');importJson.onchange=e=>{const f=e.target.files[0];if(!f||!confirm('Replace current local data with this backup?'))return;const r=new FileReader();r.onload=()=>{try{const imported=normalized(JSON.parse(r.result));if(!validData(imported))throw new Error('Invalid backup');state=imported;save();toast(`Backup imported · ${state.vehicles.length} garage vehicle(s)`)}catch{toast('Invalid backup')}};r.readAsText(f)};printReport.onclick=()=>window.print();
linkDrive.onclick=linkGoogleDrive;syncDrive.onclick=syncToDrive;disconnectDrive.onclick=()=>{sessionStorage.removeItem('mobudGoogleToken');state.settings.driveConnected=false;state.settings.storageMode='local';save()};checkUpdate.onclick=async()=>{const reg=await navigator.serviceWorker?.getRegistration();await reg?.update();toast(newWorker?'Update available':'You are using the latest loaded version')};replayTutorial.onclick=()=>startTutorial();requestBtn.onclick=()=>openFeedback('request');bugBtn.onclick=()=>openFeedback('bug');cancelFeedback.onclick=()=>feedbackModal.classList.add('hidden');feedbackForm.onsubmit=async e=>{e.preventDefault();if(!APP_CONFIG.SUPPORT_ENDPOINT_ENABLED){const p=feedbackPayload();navigator.clipboard?.writeText(JSON.stringify(p,null,2));toast('Support endpoint is not enabled yet; report copied to clipboard.');feedbackModal.classList.add('hidden');return}try{const r=await fetch(`${API}/support`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(feedbackPayload())});if(!r.ok)throw 0;toast('Report sent');feedbackModal.classList.add('hidden')}catch{toast('Could not send report')}};
onboardAddVehicle.onclick=()=>openVehicle();onboardNext1.onclick=()=>{onboardingStep1.classList.add('hidden');onboardingStep2.classList.remove('hidden')};onboardBack2.onclick=()=>{onboardingStep2.classList.add('hidden');onboardingStep1.classList.remove('hidden')};onboardNext2.onclick=()=>{onboardingStep2.classList.add('hidden');onboardingStep3.classList.remove('hidden')};onboardBack3.onclick=()=>{onboardingStep3.classList.add('hidden');onboardingStep2.classList.remove('hidden')};finishOnboarding.onclick=finishOnboardingFlow;tutorialSkip.onclick=()=>tutorial.classList.add('hidden');tutorialNext.onclick=()=>{if(++tutorialIndex>=tutorialSteps.length){tutorial.classList.add('hidden');return}showTutorial()};
const installBanner=document.getElementById('installBanner'),installNow=document.getElementById('installNow'),installLater=document.getElementById('installLater');
function isInstalled(){return matchMedia('(display-mode: standalone)').matches||navigator.standalone===true}
function hideInstallBanner(){installBanner?.classList.add('hidden')}
window.addEventListener('mobud:languagechange',()=>{state.settings.language=window.MOBUD_I18N.language;try{localStorage.setItem(KEY,JSON.stringify(state))}catch{};render()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;if(!isInstalled())installBanner?.classList.remove('hidden')});
installNow?.addEventListener('click',async()=>{if(!deferredPrompt)return;await deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;hideInstallBanner()});
installLater?.addEventListener('click',()=>hideInstallBanner());
window.addEventListener('appinstalled',()=>{deferredPrompt=null;hideInstallBanner()});
if(isInstalled())hideInstallBanner();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').then(reg=>{reg.addEventListener('updatefound',()=>{const w=reg.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'&&navigator.serviceWorker.controller){newWorker=w;updateBanner.classList.remove('hidden')}})})});applyUpdate.onclick=async()=>{downloadBackup('before-update');toast('Safety backup downloaded. Updating MoBud…');await new Promise(r=>setTimeout(r,500));newWorker?.postMessage({type:'SKIP_WAITING'})};navigator.serviceWorker?.addEventListener('controllerchange',()=>location.reload());
tripDate.value=expenseDate.value=todayISO();onboardLanguage.value=state.settings.language||window.MOBUD_I18N?.language||'en';window.MOBUD_I18N?.setLanguage?.(state.settings.language||window.MOBUD_I18N?.language||'en');applyTheme();fillLocations();render();checkCommuteReminder();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')checkCommuteReminder()});if(!state.onboardingComplete)onboarding.classList.remove('hidden');

async function fetchPartnerMetadata(urlInput,prefix){const url=urlInput.value.trim();if(!url){toast('Enter a website first.');return}try{toast('Looking up public contact details…');const r=await fetch(`${API}/metadata?url=${encodeURIComponent(url)}`);if(!r.ok)throw new Error();const d=await r.json();const map={seller:['vehicleBoughtFrom','vehicleSellerPhone','vehicleSellerAddress'],lease:['vehicleLeasePartner','vehicleLeasePhone','vehicleLeaseAddress'],maintenance:['vehicleMaintenanceProvider','vehicleMaintenanceContact','vehicleMaintenanceAddress'],insurance:['vehicleInsurance','vehicleInsurancePhone','vehicleInsuranceAddress']};const ids=map[prefix];if(d.name&&!document.getElementById(ids[0]).value)document.getElementById(ids[0]).value=d.name;if(d.phone&&!document.getElementById(ids[1]).value)document.getElementById(ids[1]).value=d.phone;if(d.address&&!document.getElementById(ids[2]).value)document.getElementById(ids[2]).value=d.address;toast(d.name||d.phone||d.address?'Public details added — please verify them.':'No public contact details found.')}catch{toast('Could not retrieve public contact details. You can enter them manually.')}}
vehicleType.addEventListener('change',()=>updatePowertrainOptions(vehicleType.value));document.querySelectorAll('[data-fetch-partner]').forEach(b=>b.addEventListener('click',()=>fetchPartnerMetadata(document.getElementById(b.dataset.urlInput),b.dataset.fetchPartner)));
['settingName','settingLanguage','settingCurrency','settingUnit','settingTheme','settingCountry','commuteReminderMode','dailyReminderTime','weeklyReminderDay','weeklyReminderTime','backupFrequency','reportFrequency','notifyUpdates'].forEach(id=>{const el=document.getElementById(id);if(el){el.addEventListener(id==='settingName'?'input':'change',autoSaveSettings)}});
